### ISSUE TITLE
On importing events in react-calendar shows different timings in classic and modern pages.

### ISSUE THREAD

**Issue by ankurihg** [pnp/sp-dev-fx-webparts#1107]
I am importing events from "site contents" site url using properties panel. when imported the timings in the modern pages comes different w.r.t classic web page. 

Can someone help me regarding this issue?

**Comment by hugoabernier** [comment]
Closing this issue as incomplete.

If you're still experiencing this issue, feel free to open a new issue. When you do, please take the time to fill the issue template provided so that we can help you better.

Please note that authors do not get automatically notified unless you fill the template that's provided.
