### ISSUE TITLE
react-facebook-plugin does not work in Chrome

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1114]
- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@koltyakov 

## Expected or Desired Behavior
Webpart would work both in Chrome and Edge.

## Observed Behavior
Webpart works great in Edge (right side of screenshot)
I only see a whitespace in Chrome (left side of screenshot 1 )

Also, not sure if this is a problem but I also see a lot of purple 'request' lines while running gulp serve (screenshot 2 ).  Would this cause any problems later on?
 
## Steps to Reproduce
1. npm install
2. npm install on-el-resize
3. gulp serve

## Chrome is on left, Edge is on right
![2020-01-14 00_24_40-SharePoint Web Part Workbench and 28 more pages ‎- Microsoft Edge](https://user-images.githubusercontent.com/49648086/72316646-e1bb4f00-3664-11ea-8f2c-29fb1108724a.png)

## I have about 50 rows of the purple 'request' lines running gulp serve.
![2020-01-14 00_07_20-FacebookPage tsx - Social-iis-7 - Visual Studio Code](https://user-images.githubusercontent.com/49648086/72316659-e5e76c80-3664-11ea-9e5f-9597a82acd35.png)

**Comment by petkir** [comment]
Hi @mikezimm 

Do you have this issue now? Because I cloned this Repo and it works as expected in Chrome and Edge Chromium 
```
cd samples\react-facebook-plugin
npm install
gulp serve
```

have you tried spfx doctor from [Office 365 CLI](https://pnp.github.io/office365-cli/) ?
```
office365
o365$ spfx doctor
```

Please take Attention this is an SPFX v1.5.1 Solution 
[spfx compatibility matrix ](https://tahoeninjas.blog/2019/12/30/spfx-compatibility-matrix/)

SPFx | Node.js | NPM | TypeScript | React
-- | -- | -- | -- | --
1.5.1 | LTS 6.x, LTS 8.x | v5 | v2.4 | v15.x

best regards

**Comment by bcameron1231** [comment]
Thanks @petkir , I also cannot reproduce and it's working for me. 

We are going to close this ticket as we haven't heard from the author for 21 days and can't reproduce. 

If this is still an issue, please re-submit the issue.

**Comment by mikezimm** [comment]
Thanks @petkir  and @bcameron1231 , I forgot about this one since I put the project using it on hold for a while.
I'll try to pull the latest version and test when I get time an also be sure I upgrade my project.

Thanks again for the followup!
