### ISSUE TITLE
Search Refiner not showing column name

### ISSUE THREAD

**Issue by spo365** [pnp/sp-dev-fx-webparts#1172]
Search Refiner not showing column name when we select filter.
![image](https://user-images.githubusercontent.com/5062256/76476368-ee3a0900-6455-11ea-947c-1fc5630a97e5.png)

**Comment by Harshagracy** [comment]
I see only two refiners selected. What other refiners did you select?

**Comment by ankitpandey09** [comment]
As i have selected 2 refiner **Created Date** and **Size of the file** but in filter section it shows onw column name which **Created Date** 

![image](https://user-images.githubusercontent.com/5062256/76493477-cfa03600-6486-11ea-9384-f853d728eb29.png)

**Comment by Harshagracy** [comment]
Can you please show the screenshot of the refiner panel after clicking the Filters?

**Comment by ankitpandey09** [comment]
Please have a look

![image](https://user-images.githubusercontent.com/5062256/76496967-3543f080-648e-11ea-9a58-88a55ccc1152.png)

**Comment by hugoabernier** [comment]
Closing this issue as there isn't enough information to help you.

If you're still experiencing this issue, feel free to open a new issue. When you do, please take the time to fill the issue template provided so that we can help you accordingly. Things like sample name, author, environment information are useful for routing the issue to the right people who can help you.
