### ISSUE TITLE
pnpjs usingCaching() is not working with .getAll() Method

### ISSUE THREAD

**Issue by ArunRajiv** [pnp/sp-dev-fx-webparts#1273]
## Question
I have been implementing spfx webpart with @pnp/Js and below is my piece of code. As per documentation [here](https://pnp.github.io/pnpjs/odata/caching/#per-call-configuration), .get() method is used for getting the items in the list which is working fine and it is also saving only 100 records in the local storage caching. 

Can I expect this caching to work with .getAll() method too or it is designed to support only .get() method?
below is my piece of code.

   sp.web.lists.getByTitle("ResourcesMaster")
                .items
                .select("Title", "ValueForKey")
                .filter("Locale eq 'en'")
                .usingCaching({
                    expiration: dateAdd(new Date(), "minute", 10),
                    key: "My Key",
                    storeName: "local"
                })
                .getAll()
                .then(async (items: any): Promise<void> => {
               console.log(items) ;
               }

**Comment by ArunRajiv** [comment]
@patrick-rodgers @koltyakov Please help me out with this clarification. any inputs from your end is highly appreciated?

**Comment by koltyakov** [comment]
Hi @ArunRajiv,

I'd consider, you can't expect data caching with `getAll` helper due to the nature of how it works and what's `getAll` is and for what use cases it's created. At least for me `getAll` and `useCaching` in a combination make little sense.

Also, in your sample `getAll` is used together with a filter condition, that won't work. Get all helper should be used only for long-running (and mostly server-side) operations, with no filtering and ordering applied (this is a MUST-have condition) when a large list content should be retrieved within sync or data preparation process, etc. Get all retrieves items by paged chunks from the large lists, it makes little sense for a usual requests when all the data can be fetched in one chunk.

The request in the sample above will fail right after the throttling comes into play. Because of the filtering. And before throttling is the case, `.get()` is better be used with reasonable `.top()` limit. With `.get()` you can expect caching to work. With `getAll` server-side processing also can cache but on its own.

**Comment by dpoum** [comment]
Hi. Should the control scroll as a carousel hiding birthdays in the past and showing newest one?

**Comment by ArunRajiv** [comment]
That makes sense.! Thanks for your guidance  @koltyakov.
