### ISSUE TITLE
React-content-query-webpart Version field

### ISSUE THREAD

**Issue by bonm014** [pnp/sp-dev-fx-webparts#1294]
## Sample
react-content-query-webpart

## Authors
@PopWarner, @hugoabernier, @PaoloPia, @spplante 

## Question
I have used this sample within my SharePoint environment in order to show files from a specific library. All goes well except the Version of the file, I can not seem to find the correct field reference in order to show the file version.
The fields that I have tested 'owshiddenversion', '_UIVersion', '_UIVersionString', 'ContentVersion', and also the raw, text or html version. None of the seems to deliver the file version...

## Question
How can I display the file version (1.0, 2.1, etc) for files of a library?

**Comment by spplante** [comment]
@bonm014  I believe the version isn't stored in list item fields but rather in the **item.File.Versions** property which isn't an item field in itself...At least that how people get the version using CSOM so it most likely means you won't be able to display it without modifying the WebPart code in order to manually add the **File** property with its children properties to the handlebars context.

**Comment by bonm014** [comment]
That is too bad, I tried to update the webpart but I seems to be unable to build it.
So I made a postrender function to additionaly get the file version via the rest api

**Comment by spplante** [comment]
A post render is a good workaround, good call 👍 

As for the build, make sure you use the 4.1.1 version which is zipped at the root of the folder, so unzip that version and try to build it instead!
