### ISSUE TITLE
React-FAQApp 

### ISSUE THREAD

**Issue by Abiman194** [pnp/sp-dev-fx-webparts#1313]
The FAQ opens up the accordion the first time, second time when the user clear off the suggestion and hits enters it doesn't do anything.  Also the second time search goes to the same accordion view to the answer and not to the current search criteria. And the FAQ suggestion questions stays there as if the screen is frozen and the user has no way to come out of the view except the reload the page. Any fix for this?

**Comment by hugoabernier** [comment]
Closing this issue as incomplete. 

If you still need help with this issue, feel free to open a new issue and fill the template so that we can help you accordingly.

Please note that sample authors do not get notified unless you fill the template as per the instructions.

Thanks for your understanding.
