### ISSUE TITLE
How to resolve "Failed to fetch" error from the react-pnpjs-project-online project?

### ISSUE THREAD

**Issue by guptarajesh001** [pnp/sp-dev-fx-webparts#1327]
When I have deployed thereact-pnpjs-project-online  project on SharePoint online and click on "Get all projects" button on screen, its through errors "GET https://wwww.contoso.com/sites/workbench/_api/ProjectServer/Projects net::ERR_NAME_NOT_RESOLVED" and "Uncaught (in promise) TypeError: Failed to fetch". How to resolve this issue?

**Comment by hugoabernier** [comment]
Closing this issue as invalid. 

If you're still experiencing this issue, feel free to open a new issue. If you do, please take the time to fill the issue template that's provided so that we can help you accordingly.

Please note that sample authors do not get notified unless you fill the template.

Thanks for your understanding.
