### ISSUE TITLE
Should I ignore vulnerabilities reported by npm Install?

### ISSUE THREAD

**Issue by RA1449** [pnp/sp-dev-fx-webparts#1347]
react-script-editor

@wobba 

After NPM install I get: added 2035 packages from 1124 contributors and audited 2047 packages in 788.077s  found 13132 vulnerabilities (5649 low, 13 moderate, 7470 high)

Afterward I run npm audit fix and get: added 51 packages from 58 contributors and updated 5 packages in 51.739s
fixed 11144 of 13132 vulnerabilities in 2047 scanned packages
  1981 vulnerabilities required manual review and could not be updated
  1 package update for 7 vulnerabilities involved breaking changes

Should I ignore all of these vulnerabilities before and/or after the npm audit fix since I understand that the SPFx provided by Microsoft is the cause?

**Comment by hugoabernier** [comment]
@RA1449 Most samples in this repository use many NPM packages that were deemed valid when the samples were created, but as new potential vulnerabilities are identified, the NPM registry flags them.

It is often a good idea to try running `npm audit` and manually update as many NPM packages that are listed, but there are no guarantees that the solution will continue to work. Running `npm audit fix` rarely works (that's why it is better to update the packages manually).

If you store the solution to GitHub, it will automatically give you security vulnerabilities reports and recommended actions; it is always recommended to follow the security advisories.

Ultimately, it is up to you (and your corporate policies) to decide whether you accept the risks of using open source solutions.

That is why every sample comes with the following disclaimer:

> Disclaimer
> THIS CODE IS PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.

I hope this helps?

**Comment by wobba** [comment]
Also for SPFx projects this mostly apply to the internal packages needed for SPFx, and not the web part itself. For most cases this can be safely ignored imo for SPFx parts.
