### ISSUE TITLE
Using URL Data Source: react-adaptivecards

### ISSUE THREAD

**Issue by cconrado** [pnp/sp-dev-fx-webparts#1348]
## Sample (which sample are you talking about)
react-adaptivecards

## Authors
@hugoabernier 
@pschaeflein 

## Question (the more details, the better)
Looking how the url data source works. I'm assuming its just hosting a json file but that's not working for me.

**Comment by hugoabernier** [comment]
I didn't get a change to try the URL function other than when @pschaeflein showed it to me, but try these steps:

1. Set the URL in the property pane to point to the JSON
2. Close the web part pane and save
3. refresh the page

Then take a look on your browser's Dev toolbars to see if you get any network issues. It could be due to proxy or CORS issues.

If it's a CORS issue, try using something like:
`https://cors-anywhere.herokuapp.com/(followedbyyoururl)`

I hope this helps?

**Comment by cconrado** [comment]
You mean like this?
![image](https://user-images.githubusercontent.com/9168464/85215060-cb629f00-b338-11ea-944b-85790b31fab8.png)

**Comment by hugoabernier** [comment]
That looks about right, but I believe you need to close the property pane, save the page, and refresh the page. 

Let us know if you find any errors in your browser's developer tools **Network** or **Console** tab.

**Comment by cconrado** [comment]
@hugoabernier found its a cors issue. I'm hosting from Azure Blob

Missing required request header. Must specify one of: origin,x-requested-with
