### ISSUE TITLE
CORS issue with react-accordion-section in local workbench

### ISSUE THREAD

**Issue by BassemNKhalil** [pnp/sp-dev-fx-webparts#1386]
## Sample (which sample are you having trouble with)
react-accordion-section

## Authors
@ejbenke

## Expected or Desired Behavior
The accordion can render in local workbench using mock lists

## Observed Behavior
![image](https://user-images.githubusercontent.com/11630074/87432491-68a8ae80-c62b-11ea-8932-4c4e44da69de.png)

## Steps to Reproduce
# Steps to reproduce the behavior:
1. clone the repo
2. npm install
3. gulp serve
4. add the webpart in the local workbench

# Environment Details (*Development & Target environment*)
- **OS**: MacOS
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8
- **Browser(s)**: Chrome & FireFox
- **Tooling**: SPFx v1.10.0

**Comment by hugoabernier** [comment]
@BassemNKhalil thanks for creating the issue, however I'm not the author of the sample, only the pr approver.

**Comment by BassemNKhalil** [comment]
Hey @hugoabernier, I tried tagging the owner listed in the solution section first @erikjbenke but it seems the account is not valid so I thought I’d revert to you - sorry I didn’t include that in the issue description

**Comment by ejbenke** [comment]
@BassemNKhalil - thank you for your interest in the sample.  I'm looking into this now.

**Comment by ejbenke** [comment]
Hi @BassemNKhalil - The local workbench is not fully supported for testing this web part.  Please use the remote workbench for your testing by appending ```/_layouts/15/workbench.aspx``` to your SharePoint Online site URL when running ```gulp serve --nobrowser```.  This will work and be far more useful anyway because you can test with real list data from your site.

I very much appreciate you bringing this up, however, because I could make this more clear in the README.md;  I'll make some updates.  Thanks again!

**Comment by hugoabernier** [comment]
Hi @BassemNKhalil I hope that you were able to resolve this issue with @ejbenke's help.

I'll go ahead and mark this issue as closed, but if you're still experiencing issues, please feel free to open a new issue.
