### ISSUE TITLE
problem when using react-list-form

### ISSUE THREAD

**Issue by clewmas** [pnp/sp-dev-fx-webparts#1443]
## Sample (which sample are you having trouble with)

react-list-form

## Authors

@harshagracy
@hugoabernier

## Expected or Desired Behavior

Possible to use web part "List Form".

## Steps to Reproduce

1. Use command gulp serve.

![image](https://user-images.githubusercontent.com/60599150/90131097-da2f6600-dd6b-11ea-9056-c9ae13227f33.png)

Or when the sppkg is deployed to a site collection app catalouge:

1. Create new page
2. Add List Form web part

![image](https://user-images.githubusercontent.com/60599150/90131063-c84dc300-dd6b-11ea-857b-1e811b47dc66.png)

# Environment Details (*Development & Target environment*)

- **OS**: Microsoft Windows Server 2016 Standard
- **Target Environment**: SharePoint Server 2019 OnPremise
- **Framework**: Node.js v10.18.0
- **Browser(s)**: Chrome v76.0.3809.132
- **Tooling**: VS Code 
- **Additional details**: The sppkg is deployed to a site collection app catalogue or when i used command gulp serve.

**Comment by Harshagracy** [comment]
Hi @clewmas ,

SharePoint 2019 supports SharePoint Framework client-side web parts hosted on classic or modern SharePoint pages built by using the SharePoint Framework **v1.4.1**. SharePoint 2019 also supposed SharePoint Framework extensions hosted on modern SharePoint pages built using SharePoint Framework v1.4.1 **This means that when you are targeting the SharePoint 2019 platform, you need to use the SharePoint Framework v1.4.1 due to the server-side version dependencies.**

The above webpart uses SPFx v1.10.0 which is not supported in on-premise.

Reference:[https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-support#which-version-of-the-sharepoint-framework-to-use](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-support#which-version-of-the-sharepoint-framework-to-use)
