### ISSUE TITLE
FluentUI-Issue-Tracker-Rollup

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-webparts#1466]
## Sample Description (what should it do)
The solution will collect open issues from multiple Issue Tracker lists (Issue Tracker is one of the new list templates that come with Microsoft Lists). The retrieved items will be displayed in a Fluent UI details list, with color coding based on the status.

In a second phase, I plan to add a chart to the sample.

## Are you Willing to Help?
I am building the solution. I am hoping to get advice from the community on specific points below.

1. Are there canonical samples that I can use as reference. In particular I am looking for solid examples of ReadMe and property pane. It seems natural to use Fluent UI for the pane in this sample, but I'd be interested to hear about other options.
2. Are we open to Teams samples, or is the repository specifically for SharePoint?
3. Any suggestions to make the sample more useful?

**Comment by hugoabernier** [comment]
Hey @PathToSharePoint  it looks like it would be a great sample.

In answer to your questions, here are my recommendations:
1. Since the samples are intended to show others how to write web parts, the more you put in your README, the better. I tend to be very verbose with mine (see https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-adaptivecards and https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-enhanced-powerapps), but as long as you use the [README.md template](https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/README-template.md) and make sure that you explain to people how to properly configure your web part, it should be good.
2. We are! Submit your samples at https://github.com/pnp/teams-dev-samples
3. I find that the best samples tend to have the following elements:
  a. Localized content
  b. No use of hard-coded color
  c. Leverages Fluent UI and do not introduce another UI framework (unless that's the intent of the sample)
  d. Focuses on code legibility over _coolness_.  Even better if you include a CodeTour to walk people through your code. 

We look forward to your sample. If you need me to review it, or if you need any help putting it together, please don't hesitate to reach out.

**Comment by PathToSharePoint** [comment]
That's very helpful, thanks! I didn't notice there was a repo dedicated to Teams.

I'll be interested to understand what you mean by "CodeTour", but let me get the code out first :-)

**Comment by hugoabernier** [comment]
@PathToSharePoint  CodeTour is an extension for Visual Studio Code that lets you create tours through your code. You can install it from: https://aka.ms/codetour 

If you're looking for inspiration, some of the newest web part samples have CodeTours that shows how to get started.

**Comment by PathToSharePoint** [comment]
A quick update on this. As it turns out, there are several moving pieces to this project, so I'll probably just close this thread and deliver in smaller bites.

The issues I have been facing:
- Retrieval of Issue Tracker lists:  modern list templates all have the same type (custom, 100), so currently I don't have an easy way to filter the list of lists. I have calledfor help: https://github.com/pnp/pnpjs/issues/1360
- Cascading dropdown in the property pane: I found the example in the official docs really scary so I decided to switch to a functional approach. For the record the official tutorial:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties
- List merge: that should be the easy part after I figure out the points above

**Comment by PathToSharePoint** [comment]
I am closing the thread as planned with a last status update:
- Confirmation that there is no easy way to tell modern lists apart as they are all based on the 100 template. So basically the plan is to retrieve all lists and trust the user to pick the right ones in the dropdown.
- I have figured out the cascading dropdowns. I also found another way to do it in the Adaptive Cards Hook sample.
