### ISSUE TITLE
Monster sp-dev-fx-webparts

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-webparts#1483]
I cloned sp-dev-fx-webparts to explore a couple solutions and answer forum questions.

In no time I found myself having to deal with a huge repository of a million files. And VS Code shows thousands of pending changes, many related to samples I didn't even explore.

Are there recommended practices to prevent this monster growth? Am I doing something wrong?

Also, would it make sense to split sp-dev-fx-webparts into smaller chunks?

**Comment by hugoabernier** [comment]
@PathToSharePoint, unfortunately, GitHub does not provide the ability to download individual folders. 

Although the repository is very large, we have found over the years that users found it easier to find all samples in one place -- regardless of the size -- instead of having multiple repositories.

I would suggest trying something like the GitHub Refined Chrome extension, which adds the ability to download individual folders from a repository.

Thanks for your feedback. We'll definitely continue to look for ways to improve this repository.
