### ISSUE TITLE
modern Script - Jira Widget

### ISSUE THREAD

**Issue by sheiknaveed87** [pnp/sp-dev-fx-webparts#1508]
Dear Team,
Can anyone help me on how can I embed jira widget on sharepoint modern page. I am able to embed the below script in classic sharepoint site. Also I can use this code in an html page which workd fine. Below is how it should look.
<script data-jsd-embedded data-key="xxxxxxxxxxxxxxxxxxxx" data-base-url="https://jsd-widget.atlassian.com" src="https://jsd-widget.atlassian.com/assets/embed.js"></script>

![image](https://user-images.githubusercontent.com/60902125/93638090-bf55ae80-fa07-11ea-9bf5-741a5ab20999.png)
![image](https://user-images.githubusercontent.com/60902125/93638108-c7155300-fa07-11ea-859d-7854951ebf1e.png)

**Comment by PathToSharePoint** [comment]
Before trying to embed this generic widget, did you look into custom connectors that Atlassian might make available to Microsoft 365 users? I don't know about SharePoint (check the marketplace), but I know that for Microsoft Teams there are Jira connectors for both server and cloud.

If you really need this specific widget, there are solutions around to replicate in SPFx the behavior of the classic CEWP. I didn't see any in this repository though, I guess that's because it's not considered a best practice.

**Comment by sheiknaveed87** [comment]
I checked with Atlassian support team. They do not have any custome
connector. Even i checked in sgarepoint store.

**Comment by sheiknaveed87** [comment]
I was thinking, you might help me in this

**Comment by PathToSharePoint** [comment]
Sure! I might have some suggestions, but let's first see what others who know the repository better have to say.

**Comment by sheiknaveed87** [comment]
@PathToSharePoint , can you help me to resolve this case

**Comment by PathToSharePoint** [comment]
Here is a solution you could try:
https://spjsblog.com/modern-cewp/

Disclaimers:
- as I said above this is not a best practice, rather a quick fix
- I haven't tried the solution myself, I just know the site as a reputable source

**Comment by sheiknaveed87** [comment]
I tried this but still it doesnt show on the modern sharepoint page

**Comment by PathToSharePoint** [comment]
If you are having an issue with that specific Web Part, I would recommend to contact the author on his forum:
https://spjsblog.com/forums/forum/modern-cewp/

**Comment by sheiknaveed87** [comment]
other code world but this specific code dosent work.

**Comment by PathToSharePoint** [comment]
I talked to the Microsoft dev team and they had two suggestions.

The first one is what I already suggested: use a third party custom CEWP. This removes the safety net offered by SPFx and you are on your own. If your specific code doesn't work, again I would recommend to talk to the Web Part author directly and be specific about the error message you are getting.

The second option is a lot more involved and AFAIK there is no solution published, so no guarantee it would work. The idea is to use the Teams SDK instead of SPFx, and build a custom solution that leverages the Jira connectors. Then you can package the Teams solution to publish it on SharePoint.

**Comment by PopWarner** [comment]
Hi @sheiknaveed87...Thank you for the inquiry.

Are you looking to have the JIRA component displayed on every page within a site collection or only a specific page?

If you are looking to display it only on a single page, then as @PathToSharePoint pointed out, a CEWP could be used for you.

Although, I believe you are likely wanting to display the JIRA assets on every page in your desired site collection.

This can be easily accomplished using an SPFx Application Customizer Extension. From my experiences integrating JIRA, their JS is fairly unobtrusive and will absolutely position the JIRA call to actions within the DOM.

The SharePoint documentation provides an excellent tutorial on creating an SPFx Application Customizer extension. The SPFx AC allows you to include custom functionality that is loaded on every page in the Site Collection where the AC is installed.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension

**Comment by PathToSharePoint** [comment]
@sheiknaveed87 I just released a "Dangerous Content Web Part" that is meant as a replacement for a classic CEWP.

The current version is 0.9.1 and license is MIT - use at your own risk. You can download the sppkg file from github directly:
https://github.com/PathToSharePoint/dangerous-content-web-part/tree/main/sharepoint/solution

I also found out that sp-dev-fx-webparts has a sample for this purpose:
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor
