### ISSUE TITLE
React directory 

### ISSUE THREAD

**Issue by kirti-prajapati** [pnp/sp-dev-fx-webparts#1513]
Is it possible to exclude disabled users accounts in search result?

**Comment by hugoabernier** [comment]
Hey @kirti-prajapati , you should reopen this issue as an idea for improvement and fill the template that is provided. 

Because of how the repo is set up,  sample authors don't get notified unless you fill the templates accordingly. 

I'll go ahead and mark this issue as incomplete,  but I think this is a great idea for improvements and it should absolutely be logged.

Thanks for your understanding
