### ISSUE TITLE
react-list-form: SPFieldLookupEdit.tsx needs update

### ISSUE THREAD

**Issue by riubaring** [pnp/sp-dev-fx-webparts#1539]
Thank you for the excellent work. I think the SPFieldLookupEdit.tsx could use a couple of edits.

Here are the recommended updates:
- Lines 23 - 25
`values = props.value.split(';').map(v => ({ key: Number(v.split(';#')[0]), text: v.split(';#')[1] }));`
- Lines 38 - 46
`function getUpdatedValue(oldValues: Array<{ key: number, text: string }>, item: IDropdownOption): string {`
`   let newValues: Array<{ key: number, text: string }>;`
`    newValues = item.selected ? [...oldValues, { key: Number(item.key), text: item.text }] : oldValues.filter((i) => i.key !== item.key);`
` `
`    return newValues.map(v => `${v.key};#${v.text}`).join(';');`
`}`

**Comment by hugoabernier** [comment]
Thanks @riubaring, unfortunately we can't help you unless you take the time to fill the issue template so that we can track which issue you're talking about, and who authored the sample.

Feel free to open a new issue, filling the issue template with the required detailed.

We also accept pull requests directly, if you'd like to submit the fixes yourself? If you are unsure of how to create a pull request, I encourage you to sign up for https://aka.ms/sharing-is-caring, where we show you hands-on guidance through creating your first pull request.

Thank you again!
