### ISSUE TITLE
Search Webparts not loading on unmanaged device with web-only access

### ISSUE THREAD

**Issue by sdevreese** [pnp/sp-dev-fx-webparts#1545]
## Question

PnP Search webpart is not loading on unmanaged devices with web-only access policy activated. Is this a common issue? Any way to resolve this?

here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/72727150/95712985-0e3cdf80-0c66-11eb-8ccc-c1c9f6e35f5e.png)

**Comment by hugoabernier** [comment]
@sdevreese I would recommend that you open a new issue (choose the **bug** template) and fill the issue template, including the sample name, author, and your environment information so we can help you accordingly.

The error seems to be specific to the PnP Property Controls. If the web part isn't deployed, make sure that you're currently running `gulp serve`. You can also try re-installing the PnP Property Controls ([the instructions](https://pnp.github.io/sp-dev-fx-property-controls/) say to use `npm install @pnp/spfx-property-controls --save --save-exact`.

I'll go ahead and close this question, but I look forward to seeing your bug report so that we can help you diagnose this further.
