### ISSUE TITLE
In js-adavanced-comments, .comment is not a funtion

### ISSUE THREAD

**Issue by nilesh-verma** [pnp/sp-dev-fx-webparts#1562]
sometimes it shows .comments function not exist, if it is added with other webparts in which jquery is used.
![Untitled](https://user-images.githubusercontent.com/51993747/97204241-dd1eec00-17db-11eb-8792-8691735e7c40.png)

**Comment by hugoabernier** [comment]
Thanks for filling this issue @nilesh-verma , but in order to properly help you with this issue, you'll need to follow the issue template that is provided and fill all the required sections. 

I'll mark this issue as incomplete.

**Comment by nilesh-verma** [comment]
which template you are talking about? please let me know

**Comment by hugoabernier** [comment]
@nilesh-verma  thanks for following up.

If you go to https://github.com/pnp/sp-dev-fx-webparts/issues/new?assignees=&labels=type%3Abug&template=bug.md and fill the sections (e.g. `# Environment Details` and `## Authors`) and follow the prompts (e.g.: `> _(DELETE THIS PARAGRAPH AFTER READING)_`)

The templates help route the information to the right people and helps notify the authors so that they are made aware of the issue.

Thanks for your understanding!
