### ISSUE TITLE
React-Carousel-png-images are not showing in carousel 

### ISSUE THREAD

**Issue by sivanu137** [pnp/sp-dev-fx-webparts#1569]
Hi, While am using this **react-carousel**, I can see jpeg images are loading perfectly. But when it comes to png a problem occurred.
From SharePoint  Picture Library all jpeg images are fetched and shown in the carousel, but not png images.

![image](https://user-images.githubusercontent.com/31919925/97531162-9ac2fe00-19d9-11eb-8a48-b7e08e07b75b.png)

Highlighted png images are not showing up in the carousel.

![image](https://user-images.githubusercontent.com/31919925/97531405-28065280-19da-11eb-9bb5-23af317507e2.png)

**Comment by hugoabernier** [comment]
@sivanu137 thanks for opening the issue, but in order to help you, we need all the information from the issue template. 

I'll go ahead and close this issue as incomplete, but please do create a new issue and take the time to fill the template that is provided to you when you click on new bug, under issues so that we can get you the help you deserve. 

Thanks for your understanding
