### ISSUE TITLE
React Content Query WebPart - .sppkg file missing 

### ISSUE THREAD

**Issue by floriemoulin** [pnp/sp-dev-fx-webparts#1571]
Hello,

I am totally in love with the React Content Query WebPart concept. But I don't find the .sppkg file to install it on my SharePoint online site (and I am not good enough to use the other installation way).

Could you please help me ?!

Thank you.

**Comment by Abderahman88** [comment]
Hi @floriemoulin,

Do you need help with :
1) How to create the sppkg
2) Installation in SharePoint Online

[react-content-query-webpart.zip](https://github.com/pnp/sp-dev-fx-webparts/files/5461145/react-content-query-webpart.zip)

**Comment by hugoabernier** [comment]
@floriemoulin the solutions don't include the `.sppkg` files because the solutions in this repository are all intended to be used as samples -- not really to be installed as-is.

If you need help building the samples, I'd recommend that you go to https://aka.ms/sharing-is-caring and sign up for the November sessions -- where we'll show you how to configure your workstation, download the sample, and build it.

Alternatively, you can use the `.sppkg` file that @Abderahman88 kindly built and uploaded, above.

Best of luck!

**Comment by floriemoulin** [comment]
Thanks to both of you for your help.
I will sign up for one of the november session.
Until the training, I will use the wonderful sample 👍 !

**Comment by ITGeekspk** [comment]
Hi,

pzl-script-editor.sppkg is free to use for production or will be needing licensing? Please guide. I shall be thanksful

Thanks
Atiq
