### ISSUE TITLE
Sample React Birthdays not working

### ISSUE THREAD

**Issue by srinubhumadi** [pnp/sp-dev-fx-webparts#1603]
Can any one please upload the working example for birthdays webpart to show birthdays from sharepoint list.
The one we have in repository is not loading the future birthdays from sharepoint list.We can see the images in the right side pan to select birthday design or image.But after adding the webpart the birthdays are not showing

**Comment by Abderahman88** [comment]
Related issue #1599

**Comment by hugoabernier** [comment]
@srinubhumadi thanks for filing an issue, but in order to help you we'll need more information. Please take the time to fill the [issue template](https://github.com/pnp/sp-dev-fx-webparts/issues/new?assignees=&labels=type%3Abug&template=bug.md&title=) that we provide.

Also, take a look at issue #1599 to see if it helps.

**Comment by srinubhumadi** [comment]
Hi hugoabernier ,
I am able to fix the issue by looking at previous solutions.
1.Index column created for Birthday in SharePoint List.
