### ISSUE TITLE
React Content Query Webpart - display user profile image

### ISSUE THREAD

**Issue by thenewblacknz** [pnp/sp-dev-fx-webparts#1651]
## Sample
React Content Query Webpart

## Authors
@hugoabernier @PopWarner @PaoloPia 

## Question
Great web part! I am just playing around with it now. I would like to output a person field, and display their profile picture. Is it possible to grab the account name from a person field to enable this? Likewise, are standard person object properties available (like job title, department, work email)?

**Comment by fthorild** [comment]
Below has been tested Online

I agree, cool webpart, I wasn't aware it existed but seeing your question made me go have a look. I tested it and noticed that if you change the column (the people column) as per the image attached to "Name (with picture and details)" you could by altering the display template "Edit template content" in the web part achieve the profile picture at least

Note the two css rules, they clean up a little bit - maybe not 100% safe as they rely on CSS names that might change.

`.dynamic-item-fields .ms-spimn-presenceLink img {
          display:none;
      }` 
`    .dynamic-item-fields .ms-peopleux-userImgWrapper img {
          border-radius:50%;
      }`
      
Also note that you should select `htmlValue` of the Author property instead of textValue and the 3 open and close curly brackets around it.

A bit complex maybe but just to highlight the extensibility of the webpart. 

I think you can get the properties as you ask about in a similar way but I couldn't see that those properties are available out of the box so you would either have to alter the source code, add extra columns in the list or add your own scripts/templates to achieve this.

![image](https://user-images.githubusercontent.com/22765326/102907604-99accb00-4476-11eb-892a-800fb2bd0d6a.png)

**Comment by hugoabernier** [comment]
@thenewblacknz you can now use a field's `personValue` to retrieve basic information such as `mail`, `displayName`, and `image.small`, `image.medium` and `image.large` properties.

For advanced details, you can use the new integration with MGT.

For example, you could bind to an author field by using:

```handlebars
<mgt-person person-query="{{Author.personValue.email}}" person-card="hover" view="oneline"></mgt-person>
```

If you use MGT integration, make sure to approve API permissions when deploying the web part, and enable **Microsoft Graph Toolkit support** in the web part's properties.

I hope this helps?

**Comment by thenewblacknz** [comment]
Amazing! Thanks for the awesome work.
