### ISSUE TITLE
Source code in react-provision-assets

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-webparts#1653]
## Sample (which sample are you talking about)
react-provision-assets

## Authors
@VelinGeorgiev 

## Question
I must be missing something obvious. I was expecting to find React source code in the react-provision-assets sample, but I don't see any script. Where should I look?

**Comment by bcameron1231** [comment]
Great question. The web part was removed from the solution because it was not needed. The sample shows how to deploy assets using the Feature Framework, and the original Web Part was the ootb SharePoint Framework Web Part created with every SPFx solution. Rest Assured, you aren't missing anything with this web part missing!
