### ISSUE TITLE
Edit Template URl in RCQWP

### ISSUE THREAD

**Issue by cajetan77** [pnp/sp-dev-fx-webparts#1660]
Hello,

I had a question for the react content query web part while im trying to point to my own template in tempalte url as soon as i try to save the page the tempalte url field is automatically resetted why is this happening any idea

**Comment by hugoabernier** [comment]
@cajetan77 we'd love to help you, but you'll have to open an issue -- not a question -- so that we can give you the help you deserve. When you do, please take the time to open an issue ticket, including your environment, version, etc.

Make sure you also include the sample authors so that the authors are notified.
