### ISSUE TITLE
Failed to build react-calendar

### ISSUE THREAD

**Issue by brouckaertd** [pnp/sp-dev-fx-webparts#1671]
Hi,

I tried to build the react-calendar but I'm facting some kind of error.
Any idea what's wrong on my environment?

I'm executing these commands in the react-calendar.

gulp build
![image](https://user-images.githubusercontent.com/2621475/104714418-7566a600-5725-11eb-9a96-5a8b0c3da0af.png)

gulp --tasks
![image](https://user-images.githubusercontent.com/2621475/104714442-7e577780-5725-11eb-89ec-0d680210764c.png)

**Comment by hugoabernier** [comment]
@brouckaertd we'd love to help you with this, but we'll need more information in order to do so.

I'll go ahead and close this issue as incomplete, but please take the time to fill a new issue template and provide all the information requested in the template, including author, environment details, etc.

Thanks for your understanding.
