### ISSUE TITLE
react-chartcontrol: NodeJS version v10.23.2 which does not meet the requirements for running this tool.  This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0

### ISSUE THREAD

**Issue by gretchunkim** [pnp/sp-dev-fx-webparts#1691]
## Sample
[react-chartcontrol](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-chartcontrol)

## Authors
Hugo Bernier (Tahoe Ninjas, @bernierh)

## Expected or Desired Behavior

Running ```gulp serve``` should build and allow the user to preview the web part on SharePoint Workbench. 

## Observed Behavior
Receiving the following error messages and failed to build the web part after ```gulp serve```: 
> Error: Your dev environment is running NodeJS version v10.23.2 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0

## Steps to Reproduce
Follow Minimal Path to Awesome
>1. Clone this repository
>2. In the command line run:
> ```npm install```
 >```gulp serve```

# Environment Details (*Development & Target environment*)
- **OS**: Windows 10 
- **Target Environment**: SharePoint Online
- **Framework**: Node.js 10.23.2
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**:  VS Code |  SPFx v1.10.0
- **Additional details**: > at SPWebBuildRig.initialize (\samples\react-chartcontrol\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:25:19)
    at SPWebBuildRig.initialize (\samples\react-chartcontrol\node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js:15:15)
    at Object.exports.initialize (\samples\react-chartcontrol\node_modules\@microsoft\sp-build-web\lib\index.js:23:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by hugoabernier** [comment]
Thank you for providing us your environment details. The web part was built using SPFx 1.11 (which should not affect you here).

The best thing to do would be to run `m365 spfx doctor` from within the root of the solution folder to see if the [SPFx doctor](https://pnp.github.io/cli-microsoft365/cmd/spfx/doctor/) can identify any issues with your environment. To install the CLI, you should visit: https://pnp.github.io/cli-microsoft365

Let us know what you find!

**Comment by gretchunkim** [comment]
Tried the following: 
1. Installed an ran  ```m365 spfx doctor``` and it says ```Error: npm not found```, however running ```npm -v``` at the root of the solution folder indicates that there's npm v 6.14.10. 
2. Updated **SPFX 1.10** to **SPFX 1.11** - made no difference 

I did come across similar tickets (closed)without resolution... 
I'll keep searching and post one if it gets resolved. 

Thank you!

**Comment by gretchunkim** [comment]
Find out some additional information by watching [Community demo - Getting started on consuming SharePoint community GitHub sample solutions](https://www.youtube.com/watch?v=EH5voQlRd-4) - Play ```9:05``` of the video.  I'll try it tomorrow  and post soon:

 **Install** node management to switch node js versions  and rerun ```gulp serve```

**Comment by gretchunkim** [comment]
The issue is now resolved! Basically I repeated the entire process again using git clone instead  of cherry picking the sample files. 

The issue was... 
1. **Not node js version issue** and installing node management won't matter
2.  **SPFX didn't matter** as hugo mentioned 

**Method**
1. git clone the entire sp-dev-fx-webparts instead of getting copy of a portion 
2. In the command line run: ```npm install``` then ```gulp serve``` 

>**Note**: running ```npm install``` automatically ran deasync node .build.js 
Curious if there's a better way to troubleshoot... 
.> deasync@0.1.14 install C:\Guser\sp-dev-fx-webparts\samples\react-chartcontrol\node_modules\deasync
> node ./build.js

**Comment by hugoabernier** [comment]
Thanks for sharing your solution @gretchunkim. It explains why I couldn't reproduce the problem. I'll make sure to include in the Sharing is Caring sessions about using and contributing to samples.

**Comment by Test-evc** [comment]
Hi @hugoabernier, I have been trying to run the react-chartcontrol for last few days with the latest version of node and npm but it is failing in something or other. As @gretchunkim suggested, I cloned the entire 'sp-dev-fx-webparts' and that too isn't of any help.

After a lot of google in several threads I find that it is due to the older version of gulp (gulp@3.9.1) used in the solution. It in-turn uses 'graceful-fs@^3.0.0' whereas rest other npm-modules have dependency on 'graceful-fs@4.2.10'. 

Running `npm ls graceful-fs` shows the same. Likewise running `npm ls gulp` shows that  @microsoft/sp-webpart-workbench and  @microsoft/sp-build-core-tasks alone depend on gulp@3.9.1 whereas all other modules depend on gulp@4.0.2

I am finding it difficult to resolve this issue. Have tried options such as creating `npm-shrinkwrap.json` with following code:
`	{
    "dependencies": {
      "graceful-fs": {
          "version": "4.2.10"
       }
    }
  }`

But then it gets into other errors such as below:
`KeyError: '2022'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\Tools\sp-dev-fx-webparts\samples\react-chartcontrol\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Tools\\sp-dev-fx-webparts\\samples\\react-chartcontrol\\node_modules\\@microsoft\\gulp-core-build-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Tools\sp-dev-fx-webparts\samples\react-chartcontrol\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-sass
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1`

Can you guide me on the way forward?

Regards,
Krishan

**Comment by hugoabernier** [comment]
Hi @Test-evc, I just tested the sample within the remote containers for SPFx 1.11 and it worked without issues.  This sample is relatively old and is due for an upgrade. but unfortunately I don't have the cycles to upgrade it right now (I tried to do a quick, but too many of the dependencies the solution requires need to be updated and the updates introduce breaking changes).

For the records, the remote container uses Node v10.22.0 and Gulp uses v3.9.1.

Please make sure that you use an environment that is compatible with the sample. You should not have to do anything else than running `npm i` and `gulp serve` to run the sample.

**Comment by Test-evc** [comment]
Thanks @hugoabernier , thanks so much for your swift attention. As you mentioned, it works well with Node v10.22.0 and Gulp uses v3.9.1. 

I wanted to flag that it needs upgrade to work with latest versions. Thanks for giving a quick try to update it, I hope in future it may. Saw some charts with dynamic data connection. Not sure if it allows connecting the chart to a SharePoint list data table? Anyways, I will try to explore it at my end as well.

Best regards,

**Comment by gretchunkim** [comment]
@hugoabernier @Test-evc : I was all ready to use docker container and it works great on personal computer but for corporate computer it's another ball game.  Installing VM over vmware, wsl for docker is not supported. If MS can provide VM with dockers that will be a game changer :-)
