### ISSUE TITLE
is it possible to use crawled or managed Properties in pnp/sp-dev-fx Modern Script Editor Webpart?

### ISSUE THREAD

**Issue by sankara2020** [pnp/sp-dev-fx-webparts#1708]
This is more of question than an issue: 

I created a html/js gantt chart and would like to use a sharepoint list to update it. is it possible to use crawled or managed Properties in the Modern Script Editor Webpart like you can with the modern search result webpart? I tried using handlebar expressions ( {{title}}, but that doesn't work.

any help would be appreciated.

**Comment by sankara2020** [comment]
Any idea?

**Comment by sankara2020** [comment]
@hugoabernier do you know if this is possible? How can I use crawled or managed Properties in the Modern Script Editor Webpart ?

**Comment by hugoabernier** [comment]
I'm sorry @sankara2020  I'm not the author of the sample. I'd have to look at the code to find out. 

You should tag the author of the sample,  or -- better yet -- create a new issue and take the time to fill a complete issue template so that we can help you better. 

I'll close this issue as incomplete.
