### ISSUE TITLE
react content query web part - get full size banner image for news page

### ISSUE THREAD

**Issue by EllisCroney** [pnp/sp-dev-fx-webparts#1709]
I am using the react content query web part and I am trying to pull through and display the news page feature images in the rollup. I am using the {{bannerimageurl}}, but it seems to only pull through the thumbnail/preview image and not the full size one.

This is what the code looks like to call the image, which is added to a div:
style="background:url('{{BannerImageUrl.rawValue.Url}}') 

This is the url that is returned:
domain/_layouts/15/getpreview.ashx?guidSite=ce03baff27764726a546a02e5855b352&guidWeb=651bdced26ed4dc781eba9b74ad258d1&guidFile=028078648a854491927a57e0d690d143&ext=jpg

This gets this small preview image:
![image](https://user-images.githubusercontent.com/58901628/107778077-8530d480-6d3b-11eb-8ee7-20597197fcdc.png)

Please can someone help me to get the url for the full size image that is shown as the feature image of the actual news page?

thanks

**Comment by hugoabernier** [comment]
You can try getting the JSON value for the field and see if you can retrieve the full path.

Try something like this perhaps?
```
style="background:url('{{BannerImageUrl.jsonValue.serverRelativeUrl}}')
```

**Comment by EllisCroney** [comment]
Hi Hugo, thanks for the response, but that didn't return anything

**Comment by Abderahman88** [comment]
Hi @EllisCroney,

Try **Url** instead of **serverRelativeUrl**

`<img src="{{BannerImageUrl.jsonValue.Url}}"/>`

![newsNormal](https://user-images.githubusercontent.com/36161889/107891853-802d7a00-6f21-11eb-9091-fd8066992188.PNG)

If you want to change the size of the image, add the parameter `resolution `to the url in the template editor.
The `resolution`-parameter can have following values:

![resolutionSize](https://user-images.githubusercontent.com/36161889/107891906-d7334f00-6f21-11eb-9439-6adffea26725.PNG)
(Source : https://blog.vitalyzhukov.ru/en/sharepoint-online-document-thumbnail)

For full image size:
`<img src="{{BannerImageUrl.jsonValue.Url}}&resolution=6"/>`

The result is a huge image 😄 

![fullImage](https://user-images.githubusercontent.com/36161889/107891971-46a93e80-6f22-11eb-96d0-0f0f3b40fd61.PNG)

Let me know if it this answers the question for you 👍

**Comment by EllisCroney** [comment]
Adding the resolution parameters worked perfectly! Thank you
