### ISSUE TITLE
React Script Editor Webpart: Webpart doesn't show in list of webparts when you try to add to page

### ISSUE THREAD

**Issue by EllisCroney** [pnp/sp-dev-fx-webparts#1732]
I am having an issue with the react script editor webpart.

I have successfully cloned the repo, then run the necessary gulp commands to package the solution and successfully deploy to the app catalog with no errors. The app shows in the tenant site collections and I can add successfully, but then when I try to add to the page the app is not available to add. There are no errors, the webpart just doesn't appear at all (see below)
![image](https://user-images.githubusercontent.com/58901628/108904125-07f84000-7616-11eb-8b2c-fafb9ea9faec.png)

I have allowed scripts at tenant level and changed the requiresCustomScript to false in the app code.

If I run gulp serve and run the app on my local workbench it works fine. 

Please help, thanks
@hugoabernier

**Comment by hugoabernier** [comment]
Thanks for submitting the issue, but in order to help you, we need you to provide all the information we request in the issue template. 

I'll go ahead and close the issue as incomplete,  but please feel free to open a new issue with all the required information. 

Also, please note that I'm not the author of the sample.  You may want to tag the actual author(s) on your next issue so they get notified. 

Hopefully we can get you the help you deserve. 

Thanks for your understanding
