### ISSUE TITLE
Still Unavailable as a Web Part

### ISSUE THREAD

**Issue by paparush** [pnp/sp-dev-fx-webparts#1742]
Hello,
I am trying to deploy the webpart to a SharePoint 365 site.  In the tenant admin console, I have set Allow Custom Scripts to TRUE.  That was some 36 hours ago, so I feel I should be beyond the 24 hour window for changing that setting to take effect.

I have edited the ScriptEditorWebPart.manifest.json and set
"requiresCustomScript": false

This is the only line of code in the solution that I have changed.  Everything else is straight from this repo that I cloned.

I have successfully added the sppkg to the tenant's App Catalog.  Likewise, I successfully add the app to the site.

Unfortunately, the web part is not in the list of available web parts when I edit a site page.

Have I missed something?   Any assistance in resolving this issue is greatly appreciate.

**Comment by hugoabernier** [comment]
Closing this issue as incomplete. Feel free to [create a new issue](https://github.com/pnp/sp-dev-fx-webparts/issues/new?assignees=&labels=type%3Aquestion&template=question.md&title=) and fill all the required sections as per the template so that we can help you accordingly.

Thanks for your understanding.
