### ISSUE TITLE
react-staffdirectory: "Insufficient privileges to complete the operation."

### ISSUE THREAD

**Issue by tristian2** [pnp/sp-dev-fx-webparts#1752]
## Sample
react-staffdirectory

## Authors
João Mendes (joaojmendes)

## Expected or Desired Behavior

Render the search box on the webpart, when deployed to a modern page.

## Observed Behavior

Displays error message.
![Screenshot 2021-03-05 at 12 18 04](https://user-images.githubusercontent.com/1449782/110114649-e5e88580-7dac-11eb-94ea-46eb53f9594b.png)
or sometimes
![Screenshot 2021-03-05 at 12 17 53](https://user-images.githubusercontent.com/1449782/110114651-e6811c00-7dac-11eb-869e-b963fc60e48c.png)

I see a 403 in the console, for the GET request to the graph endpoint, for example

`
GET https://graph.microsoft.com/beta/users?$select=id,displayName,jobTitle,mail,mobilePhone,department,businessPhones,userPrincipalName,city,companyName,country,employeeId,imAddresses,officeLocation,postalCode,userType&$top=5&$orderby=displayName&$count=true 403 (Forbidden)`

and the response

```
staff-directory-web-…84cf2862d99c65.js:1 
{statusCode: 403, code: "Authorization_RequestDenied", message: "Insufficient privileges to complete the operation.", requestId: "9ff3e5e1-f4f9-45ce-a0b3-fe910f52e13c", date: Fri Mar 05 2021 12:22:29 GMT+0000 (Greenwich Mean Time), …}
body: {code: "Authorization_RequestDenied", message: "Insufficient privileges to complete the operation.", innerError: {…}}
code: "Authorization_RequestDenied"
date: Fri Mar 05 2021 12:22:29 GMT+0000 (Greenwich Mean Time) {}
message: "Insufficient privileges to complete the operation."
requestId: "9ff3e5e1-f4f9-45ce-a0b3-fe910f52e13c"
statusCode: 403
__proto__: Object
```

## Steps to Reproduce

Install and deploy the webpart to a page according to the documentation.

# Environment Details (*Development & Target environment*)

- **OS**:  MacOS 10.15.x
- **Target Environment**:  SharePoint Online
- **Framework**:  Node.js v10
- **Browser(s)**: [e.g. Chrome v88 | Edge 
- **Tooling**: VS Code | SPFx v1.10.0 
- **Additional details**: I have checked that endpoints are available using graph explorer

**Comment by sudharsank** [comment]
Hi @tristian2, may I know how you are running the project? try to deploy the package to the app catalog so that you can grant API permissions in SharePoint Admin center. The solution use the **MS Graph API** to retrieve the users and their presence and its using the **beta API**. Once you provided the access, the web part should work as expected. Please check the **SharePoint Admin center** --> **API Access** and you should have couple of permissions like the screenshot below. You wont see all but you should see the presence related permission which is configured in the solution **package-solution.json** file.
![image](https://user-images.githubusercontent.com/10280385/110274309-7cb17e00-8009-11eb-8c49-31d0c13033a5.png)

**Comment by tristian2** [comment]
I have solved the issue, i had to enable API access in Azure AD, for SharePoint Online Client Extensibility Web Application Principal.
Thanks for your time.
<img width="677" alt="Untitled picture" src="https://user-images.githubusercontent.com/1449782/110617514-b4493300-818d-11eb-8c4b-e596020f1048.png">
