### ISSUE TITLE
react-directory: Show external users in result

### ISSUE THREAD

**Issue by Mykie89** [pnp/sp-dev-fx-webparts#1763]
## Sample:
react-directory

## Authors:
@hugoabernier @petkir @joaojmendes @sudharsank

## Question:

How can I display external / guest users in search result?

## Details:
If I search in modern experience than search result not show external users, but in classic experience I found the external users.
I want to use react-directory sample, but this doesn't  show the external users.

## Environment:
SharePoint Online

**Comment by Mykie89** [comment]
@hugoabernier  can you help me? Is there any solution to show external users?

**Comment by hugoabernier** [comment]
@Mykie89 I'm not the original author of the sample. Although I'd be happy to look at it when I have a chance, you'd be better served with the people who actually wrote the sample.

**Comment by johanvandy** [comment]
@petkir @joaojmendes @sudharsank @Abderahman88 

I would also like this to be implemented. Maybe add a toggle to include\exclude external users\guests!

**Comment by petkir** [comment]
Hi @johanvandy @Mykie89,

This Sample is based on SharePoint People Search (```'b09a7990-05ea-4af9-81ef-edfab16c4e31'```).

As far I know is that External Users are not included in this Search Result.
If external users should be Included another method has to be implemented to get user/Contact/External User data. 

From my point, I would not change the API endpoint, because since SharePoint 2013 quite a lot of people wrote samples and blog posts to describe how to build a corporate directory based on Search. 

But you are welcome to contribute and make this toggle switch possible.
If you find a way to add external user in the people search result, it's also a possible solution without any code change.

**Comment by Ravikadri** [comment]
You might be the same search endpoint with altered query parameters. There is an excellent article from Mikael Svenson on the same. Link below

https://www.techmikael.com/2015/04/an-approach-to-listing-all-external.html

Hope it helps!

Thanks!
Ravi

**Comment by petkir** [comment]
@Mykie89 do you need any further help?
