### ISSUE TITLE
react-content-query-online: Build error running gulp serve - Module not found: Can't resolve 'readline' 

### ISSUE THREAD

**Issue by mujassir** [pnp/sp-dev-fx-webparts#1772]
**Sample**
react-content-query-online

**Authors**
@PopWarner @hugoabernier @PaoloPia

**Expected or Desired Behavior**
gulp serve should complete without errors and the web part should be working on the workbench

**Observed Behavior**

Following errors appears:

Error - [webpack] 'dist':
./node_modules/log-utils/index.js
Module not found: Error: Can't resolve 'readline' in 'C:\Workspace\react-content-query-online\node_modules\log-utils'
resolve 'readline' in 'C:\Workspace\react-content-query-online\node_modules\log-utils'
  Parsed request is a module
  using description file: C:\Workspace\react-content-query-online\node_modules\log-utils\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
.
.
.
[C:\Workspace\react-content-query-online\lib\readline.json]
 @ ./node_modules/log-utils/index.js 10:15-34
 @ ./node_modules/logging-helpers/index.js
 @ ./node_modules/handlebars-helpers/lib/logging.js
 @ ./node_modules/handlebars-helpers/lib/index.js
 @ ./node_modules/handlebars-helpers/index.js
 @ ./lib/webparts/contentQuery/components/ContentQuery.js
 @ ./lib/webparts/contentQuery/ContentQueryWebPart.js

**Comment by mujassir** [comment]
Just to mention, I have run the following command prior to building the solution (gulp serve)

`npm install`

I have tried following commands without any luck:

`npm audit fix`
`npm shrinkwrap`

Thanks in advance for your help.

**Comment by hugoabernier** [comment]
@mujassir in order to help you, we need you to provide all the details that we ask for in the issue template, including environment information.

Try providing the following information:


## Steps to Reproduce

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

> Issues without an steps to reproduce will be closed automatically 
>
> _(DELETE THIS PARAGRAPH AFTER READING)_


# Environment Details (*Development & Target environment*)

- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

Please note that normally we close issues that do not follow the issue template. We do this so that we avoid sending messages back and forth to diagnose the problem.

**Comment by mujassir** [comment]
### Steps to Reproduce

Steps to reproduce the behavior:

1. Download source code of the "react-content-query-online" web part from https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-content-query-online
2. Install dependencies
`npm install`
3. Tried to run
`gulp serve`
4. See error

Error - [webpack] 'dist':
./node_modules/log-utils/index.js
Module not found: Error: Can't resolve 'readline' in 'C:\Workspace\react-content-query-online\node_modules\log-utils'
resolve 'readline' in 'C:\Workspace\react-content-query-online\node_modules\log-utils'
Parsed request is a module
using description file: C:\Workspace\react-content-query-online\node_modules\log-utils\package.json (relative path: .)
Field 'browser' doesn't contain a valid alias configuration
resolve as module
.
.
.
[C:\Workspace\react-content-query-online\lib\readline.json]
@ ./node_modules/log-utils/index.js 10:15-34
@ ./node_modules/logging-helpers/index.js
@ ./node_modules/handlebars-helpers/lib/logging.js
@ ./node_modules/handlebars-helpers/lib/index.js
@ ./node_modules/handlebars-helpers/index.js
@ ./lib/webparts/contentQuery/components/ContentQuery.js
@ ./lib/webparts/contentQuery/ContentQueryWebPart.js

### Environment Details (Development & Target environment)

* **OS:** Windows 10
* **Target Environment**: SharePoint Online
* **Framework:** Node.js v10.13.0
* **Browser(s):** Chrome v89
* **Tooling:** VS Code

**Comment by hugoabernier** [comment]
Can you try to run [spfx doctor](https://pnp.github.io/cli-microsoft365/cmd/spfx/doctor/) from the project folder and report the results?

**Comment by mujassir** [comment]
With the command `m365 spfx doctor` it shows the following:

CLI for Microsoft 365 SharePoint Framework doctor
Verifying the configuration of your system for working with the SharePoint Framework


Error: npm not found

But npm is installed `npm -v` shows 6.4.1

**Comment by hugoabernier** [comment]
@mujassir did you ever resolve this issue? Note that the M365 CLI has been updated since to fix the issue you were experiencing.

I'll mark this issue as closed, but fele free to open a new issue if you're still experiencing issues.
