### ISSUE TITLE
sample failing to gulp serve

### ISSUE THREAD

**Issue by rmwilkins** [pnp/sp-dev-fx-webparts#1777]
## Sample (which sample are you talking about)

react-accordion

## Authors
@mikezimm 

## Question

When running gulp serve i get an error. stating primordials is not defined.  Can you please offer some advice how I can get this running. See attached.

I have run npm install had the issue.  I also followed some other advice to delete node-module directory and add npm-shrinkwrap.json specifying graceful-fs version to 4.2.2.

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (C:\spfx code\react-accordion\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\spfx code\react-accordion\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\spfx code\react-accordion\node_modules\gulp\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)

![gulp serve issue](https://user-images.githubusercontent.com/69326909/111887729-1fff8b80-8a2b-11eb-9dc0-09f5fb446198.JPG)

**Comment by hugoabernier** [comment]
Thanks for filing the issue @rmwilkins, but I'm not the author of the sample. If you want the original authors to get notified, you'll need to tag them, not me.

**Comment by rmwilkins** [comment]
Thanks @hugoabernier - just retagged to @mikezimm .

**Comment by mikezimm** [comment]
@rmwilkins ,
I'm also not one of the original authors.... I just added a property to the property pane with Hugo's help.

Based on the sample history, you may want to as @bcameron1231  or @AbhishekGarg since it looks like they have more hands on the code than I did.

Maybe start with @AbhishekGarg since he has the earlier history and may be the original creator.

![image](https://user-images.githubusercontent.com/49648086/112037242-ea849c00-8b17-11eb-94a2-34f05c04c7f3.png)

**Comment by PathToSharePoint** [comment]
@rmwilkins may I suggest to add more details about your build environment? And validate that it is compatible with the SPFx version used in the sample.
I have seen gulp serve failing, with error messages about "manifest" or "primordials", due to compatibility issues between SPFx, Nodejs, Gulp and TypeScript/tslib.

**Comment by hugoabernier** [comment]
Closing this issue as incomplete. Feel free to open a new issue with and provide all the required information, including environment details so that we can get you the help you deserve.

**Comment by bcameron1231** [comment]
For what its worth, it sounds like there is a compatibility issue with your version of Gulp/Node and this solution.  Please be aware you need to use Node 8 or 10 with this solution and gulp v3 

@rmwilkins  When you create a issue, please include this information the template provided as @hugoabernier  mentioned, and it will make it easier to diagnose.
