### ISSUE TITLE
SharePont 2019 Compatibility

### ISSUE THREAD

**Issue by alaabitar** [pnp/sp-dev-fx-webparts#1893]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-list-form

### Author(s)

@fthorild

### Question

Hello,

I would like to use this webpart in a SharePoint 2019 environment. What do I need to change to make it work ?

Best regards,
Alaa

**Comment by petkir** [comment]
Hi @alaabitar ,

You need a solution based on SPFX 1.4 for SharePoint 2019

I would start with a new SPFX project 

```yo @mirosoft/sharepoint```

at the start select SharePoint2019 and create a web part called listForm
include packages they match for the Requirements of SharePoint 2019 and React 15
For example office-ui-fabric-react you will need in version 5.x

Next step would be to copy some files from the sample to your  new Solution
```src/webparts/listForm/ ```  you have to exclude the file  ```ListFormWebPart.manifest.json```


it can happen, that you have to rewrite the code because React15 does not support ReactHooks.

Hope this will help you.

**Comment by hugoabernier** [comment]
Hey @alaabitar I hope that @petkir's response helped you resolve this issue? 

I'll go ahead and close the issue as answered, but feel free to open a new issue if you run into any further issues.

Thanks @petkir for your help with this.

**Comment by alaabitar** [comment]
Hello guys,

Yes thank you very much! I will definitively try @petkir solution and will keep you posted.

Very best regards,
Alaa
