### ISSUE TITLE
Staff Directory - The id token is null or empty. Please review the trace to determine the root cause. Raw ID Token Value:null

### ISSUE THREAD

**Issue by venkat176** [pnp/sp-dev-fx-webparts#1918]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-staffdirectory

### Author(s)

@arigunawan3023, @joaojmendes, @tristian2

### What happened?

Getting this error sometimes
![staff](https://user-images.githubusercontent.com/53978426/120188754-1f0d8600-c234-11eb-9d35-18dfcec0b276.png)

The id token is null or empty. Please review the trace to determine the root cause. Raw ID Token Value:null

### Steps to reproduce

1. Deploy the web part and assign required permissions
2. Open or edit the page where the web part added

required

### Expected behavior

It show's this error message - The id token is null or empty. Please review the trace to determine the root cause. Raw ID Token Value:null
![IdToken](https://user-images.githubusercontent.com/53978426/120189522-17021600-c235-11eb-9033-171c97789c6d.png)

Or

![toekenrnewel](https://user-images.githubusercontent.com/53978426/120189540-1b2e3380-c235-11eb-879d-a54bc5da5f1a.png)

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.11.0

### Node.js version

v10.23.1

**Comment by hugoabernier** [comment]
@venkat176 thanks for the issue. As per the issue template instructions, you might want to `@mention` the authors instead of listing their names, otherwise, they'll never get notified of the issue -- thus making it harder to get them to help you.

**Comment by venkat176** [comment]
Thanks, @hugoabernier -- Mentioned the authors.

**Comment by AriGunawan** [comment]
Hi @venkat176 ,
I just tried to update this app in my tenant from v1.0.1 to v1.0.2 (latest) and got the same error.
I'm not sure why but when I do the following:
1. Remove the web part from the page
2. Remove the app from the app catalog
3. Add the app to the app catalog and install
4. Add the web part to the page

Now it's working fine and I can't replicate the error anymore.

Are you seeing the web part title as "Search Directory" or "UoB Search Directory"?
Because I believe when I got the error, it's still showing the title as "Search Directory" while it should be "UoB Search Directory" - the title is updated on v.1.0.2
![image](https://user-images.githubusercontent.com/8691985/120461395-2c597a80-c3c4-11eb-90f6-4f373bed5eb2.png)
