### ISSUE TITLE
Webparts specifying exact versions of dependencies resulting in associated vulnerabilities.

### ISSUE THREAD

**Issue by sthorley** [pnp/sp-dev-fx-webparts#1921]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-section

### Author(s)

ejbenke

### Question

Hi,

I want to get an understanding as to why the package.json for many of these webparts specifies the exact version of the dependancy (presumably at the time the commit was made) rather than allowing for newer versions. There seems to be little maintenance to update these builds which means using exact versions increases the risk of security vulnerabilities significantly. I was recently building [React-Accordian-Section](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-section) when I was informed by Node there were 44422 vulnerabilities in the build including 14831 of high severity ones and 28 of CRITICAL severity.

Would it not make more sense to require devs committing a PR to use the version greater than syntax to allow these to compile with the latest versions of dependancies? Obviously this might cause breaking changes if large changes are made to the underlying dependancies but in this case couldn't an Issue be created by the dev having the build issue? Currently the "Minimal path to Awesome" suggests loading up out of date dependancies riddled with vulnerabilities. There are further issues where frequently dependancies depend on different versions of common libraries resulting in the build failing anyway. 

Surely it is better to have the default try to build a secure webpart and require troubleshooting to have it build correctly than to force an out of date insecure webpart? The style could even be updated to have a "Package.json using versions available when committed" and an additional "Package.json using latest versions" which would at least allow people following the minimal path to attempt to build something secure?

**Comment by hugoabernier** [comment]
@sthorley I think that you're absolutely right that it would be the best thing to do, but all our samples are contributed by and maintained by, volunteers -- including me.

We review all samples before publishing them, and the code is automatically scanned for vulnerabilities; We apply patches as soon as they are reported. Still, there can be a delay between a vulnerability being discovered and being reported in our repo.

The samples in this repo are absolutely intended to be used as samples only, and it is everyone's responsibility to make sure to apply due diligence and ensure to adhere to their organization's security guidelines --and make the appropriate modifications -- before using them in production.

That being said, we're constantly striving to improve; If you find a vulnerability, please submit a pull request or file a new security vulnerability issue and we'll use the strength of the community to try to resolve it.

If you have the time to update the `package.json` of the samples and test them, please feel free to do so. I hope that you can set the example and that it will encourage others in the community to do the same for other samples.

On a related note, if you `@mention` the author (instead of just writing their names), they'll get notified, which may significantly increase of the odds of them being aware that there is an issue.

I hope to see pull requests from you soon! And thanks again for speaking up on this issue.

**Comment by hugoabernier** [comment]
The Readme.md says that the solution uses spfx 1.10. You'll need to refer to the matrix to find which versions of node are supported (I think 8.x or 10.x). Node 14 was definitely not supported by that version of spfx
