### ISSUE TITLE
Question about debouncing in react-directory sample

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1944]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/b139ba199cb57363a88f070dd9814e5af4fc3cbd/samples/react-directory

### Author(s)

@petkir_at @sudharsank

### Question

I was looking for a simple debounce implimentation and found this sample which I had used before has one.

[DirectoryHook.tsx](https://github.com/pnp/sp-dev-fx-webparts/blob/b139ba199cb57363a88f070dd9814e5af4fc3cbd/samples/react-directory/src/webparts/directory/components/DirectoryHook.tsx)

I'm not using react hooks so my implimentation is a little different but it does not work.  I'm guessing it's a simple lack of understanding and am hoping someone can help me.

## My original function
```typescript
  private async onWebUrlChange(newValue: string){
     //Fetches info based on url typed in text box on every change
  }
```

## This is what I tried but it seems to still fire while I'm typing every character
NOTE:  I added this to the imports:
   import { debounce } from "throttle-debounce";

```typescript
  private _onWebUrlChange(newValue: string){
    debounce(250, this.debounce_onWebUrlChange( newValue ) );
  }

  private async debounce_onWebUrlChange(newValue: string){
      //Fetches info based on url typed in text box on every change
  }
```

For reference, here is a [link to my tsx file](https://github.com/mikezimm/generic-solution/blob/340c80557d95a0788bbdf93fd3afefa46770a90e/src/webparts/genericWebpart/components/GenericWebpart.tsx#L709) where I'd like to add the debounce... it's not pretty code but if it helps it helps :)

Thanks for any help getting the syntax correct!

**Comment by petkir** [comment]
Hi @mikezimm 

I hope, I understood your question right.

I would implement it in this way
**Code Snippet**
```
private deBounce(NewValue: string): void {
    this.lastValue = NewValue;
    setTimeout(() => {
      if (this.lastValue === NewValue ) {
        this.firedValue = this.lastValue;
        executeRequest(this.lastValue);
      }
    }, 200);
  }
```
**Description**
First, I save the current value.
After the debounce(setTimeout) I check if the saved value is the same as the value I saved before if they are equal I execute the ```executeRequest``` and store the input value of the Request.

This Part is not in the snippet:
As soon the request is finished I would check if the `this.firedValue === this.lastValue`, because if the request takes more time a new character is maybe entered in the text field.

**keep in mind**
As soon the ```executeRequest``` is executed the request will be sent to the server and the client is waiting for a response.
To cancel the Request would be nice and this is possible with an ```AbortController```

```
const controller = new AbortController()
    const signal = controller.signal
signal.addEventListener("abort", () => {
        console.log("aborted!")
    })
fetch('https://mylongexecution', {
                method: 'get',
                signal: signal,
            })
```
and with ``` controller.abort()``` you can stop the request.

read more https://developer.mozilla.org/en-US/docs/Web/API/AbortController

**Comment by mikezimm** [comment]
@petkir ,
Thanks for the suggestion!
I gave it a try and bombarded it with personal testing (less the this.firedValue === this.lastValue part).

I had to bump up the delay to 1000 ms because in my case, it kept firing before I was ready.  Sometimes the extra thought required to remember the exact url or if my keyboard stuck or whatever.

Anyway it works!

The only quirky thing I found "trying to break it" was that if I typed a letter than backspace repeatedly like:
a backspace a backspace a backspace a backspace a backspace

It seemed to fire without delaying.  I'm wondering if it has to do with the the old value and new value "might" somehow be equal in the timing.  Anyway, it is good enough for what I'm looking for.

Thanks!
Do you close or I?
