### ISSUE TITLE
script editor webpart not available 

### ISSUE THREAD

**Issue by jouhaina86** [pnp/sp-dev-fx-webparts#1962]
### Sample

react-script-editor

### Author(s)

@mikaelsvenson

### Question

I'm not able to see the script editor webpart after deploying an addin on the app catalog without any errors on SharePoint online. please note that I already enable the custom script on my site collection.

how can I see the webpart on the page knowing that I did all the steps as mentioned on the readme?

**Comment by Abderahman88** [comment]
@jouhaina86 Check #1744. Did you run the PowerShell script on your site collection?

**Comment by jouhaina86** [comment]
> @jouhaina86 Check #1744. Did you run the PowerShell script on your site collection?
yes already I run it

**Comment by Abderahman88** [comment]
@jouhaina86 I will test it out and let you now the result. Stay tuned. 📺

**Comment by Abderahman88** [comment]
@jouhaina86 Have you done this step?

![image](https://user-images.githubusercontent.com/36161889/126711844-d991f42d-ba21-4be7-affb-a34ba40dfbbd.png)

I tested with version 1.0.0.16 and have no issues on a new modern site.

[pnp-script-editor.zip](https://github.com/pnp/sp-dev-fx-webparts/files/6865318/pnp-script-editor.zip)

**Comment by Abderahman88** [comment]
@jouhaina86 Is the problem fixed?

**Comment by hugoabernier** [comment]
Closing this issue as answered. Thank you @Abderahman88. @jouhaina86 if you're still experiencing issues, feel free to open a new issue.

**Comment by oshihirii** [comment]
@hugoabernier 

Sorry for the non-positive comment but I believe the following needs to be communicated.  

Obviously the author/s of the app are incredibly clever to have got it working in the first place, so I acknowledge and am grateful for the original intention behind the app.  

However, I have spent two days trying to get this web part to work only to find:

 - It does not appear in the list of available web parts, even when the app has been added and enabled on a site  

 - The author says it should not be used 
    (https://www.techmikael.com/2024/03/allowing-arbitrary-custom-scripting-in.html)

For these reasons, I don't understand why `/samples/react-script-editor` is still on GitHub.  

At the very least, the README should prominently dissuade new users from attempting to get it to work.    

My steps involved:

01.  Uninstalling Node (because it needs a specific version of Node to build it)  
02.  Installing NVM for Windows and specifically installing Node 18.17.1 
03.  Cloning the repo with `git clone https://github.com/pnp/sp-dev-fx-webparts.git`  
04.  Running `npm install` and getting failure errors
05.  Running `npx update-browserslist-db@latest`  
06.  Running `npm install` again 
07.  Running `npx gulp trust-dev-cert`  
08.  Running `npx gulp serve` 
09.  Successfully testing in online workbench at `https://<my-tenant>.sharepoint.com/_layouts/15/workbench.aspx`  
10.  Running `npx gulp clean`
11.  Running `npx gulp bundle --ship`
12.  Running `npx gulp package-solution --ship`
13.  Uploading .sppkg file from sharepoint\solution to my tenant App Catalog 
       (via `SharePoint Admin Centre` > `More features` > `Apps` > `Upload`,  and then click 'Enable')   
14.  Go to `Site Contents` > `Settings Cog Icon` > 'Add an app`  and select the app  
15.  Go to a Site Page, click on Edit and find the new web part is not visible  

I repeated several of the above steps several times to make sure I wasn't missing anything.  

The site I added the app to was a normal SharePoint Online Communication Site (it is not a Teams site).  

I then came across the article from the author which strongly advises not to use it:

https://www.techmikael.com/2024/03/allowing-arbitrary-custom-scripting-in.html
