### ISSUE TITLE
npm install command error

### ISSUE THREAD

**Issue by Roberto-El-Hajj-Boutros** [pnp/sp-dev-fx-webparts#2173]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/react-mgtEvents/src/webparts/mgtEvents/MgtEventsWebPart.ts

### Author(s)

hugoabernier

### Question

Hello, 

I would like to add the react-mgtEvents web part to my SharePoint Online site. I installed the node-js version from the below URL:https://nodejs.org/download/release/v10.24.1/

After that, I tried to execute the npm install command on the react-mgtEvents folder path. However, I am getting the below errors after it finishes: What are the dependencies that should be installed for this solution to make it run successfully and upload the app to the SharePoint app catalog? Can please someone provide the steps needed?

Any help is highly appreciated.

Thank you!

@joaojmendes 
![Capture 1](https://user-images.githubusercontent.com/57991166/146787552-dbb704b7-fd2c-4b5a-a884-da7e3e39c657.PNG)

![Capture](https://user-images.githubusercontent.com/57991166/146787166-5a4d9589-7693-4822-8adb-b00a237b8e6f.PNG)

**Comment by nishant-frontier** [comment]
Roberto-El-Hajj-Boutros, please update author as Mikael Svenson (@mikaelsvenson, techmikael.com). 

I am facing same issue. Looking forward to hearing from author soon.

**Comment by EmpowerTech** [comment]
Add me to the list as well.

**Comment by joaojmendes** [comment]
Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: nishant-frontier ***@***.***>
Enviado: Tuesday, December 21, 2021 11:29:43 PM
Para: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-webparts] npm install command error (Issue #2173)


Roberto-El-Hajj-Boutros, please update author as Mikael Svenson ***@***.***<https://github.com/MikaelSvenson>, techmikael.com).

I am facing same issue. Looking forward to hearing from author soon.

-

**Comment by Abderahman88** [comment]
@Roberto-El-Hajj-Boutros Is [Python](https://www.python.org/downloads/) installed on your machine?

**Comment by pfrowe** [comment]
Add me to this list, too. I just repaired my Python installation and tried `npm install` again and got the same error.

**Comment by pfrowe** [comment]
> Add me to this list, too. I just repaired my Python installation and tried `npm install` again and got the same error.

Sorry... I'm getting a different error when I do `npm install`... I'll latch onto or create a different issue.

**Comment by Anishsid7040** [comment]
### **Add me to this list as well. Getting similar error:**

npm ERR! code 1
npm ERR! path C:\Users\apandit\sp-dev-fx-webparts\samples\react-staffdirectory\node_modules\deasync
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.3.0 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:448:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:687:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\apandit\\sp-dev-fx-webparts\\samples\\react-staffdirectory\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\apandit\sp-dev-fx-webparts\samples\react-staffdirectory\node_modules\deasync
npm ERR! gyp ERR! node -v v17.3.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\apandit\AppData\Local\npm-cache\_logs\2022-01-12T15_51_06_066Z-debug-0.log
PS C:\Users\apandit\sp-dev-fx-webparts\samples\react-staffdirectory> cd c
cd : Cannot find path 'C:\Users\apandit\sp-dev-fx-webparts\samples\react-staffdirectory\c' because it does not exist.
At line:1 char:1
+ cd c
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\apandi...taffdirectory\c:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\apandit\sp-dev-fx-webparts\samples\react-staffdirectory> cd ~
PS C:\Users\apandit> cd C:\windows
PS C:\windows> \system32
\system32 : The term '\system32' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ \system32
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\system32:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\windows> cd system32
PS C:\windows\system32> npm install -g windows-build-tools
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated windows-build-tools@5.2.2: Node.js now includes build tools for Windows. You probably no longer need this tool. See https://github.com/felixrieseberg/windows-build-tools for details.
[##################] \ reify:resolve: timing reifyNode:node_modules/windows-build-tools/node_modules/ajv Completed in 1241ms
