### ISSUE TITLE
Not able to query large lists using List Search Webpart

### ISSUE THREAD

**Issue by yvsuhas** [pnp/sp-dev-fx-webparts#2405]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-list-search

### Author(s)

@albertogperez

### What happened?

The sample works great with any data source as long as the item count is less than 5000 and it is hitting the view threshold even though we specify a view which has items less than 5000. I've checked the network and observed that the rest api calls are hitting the default list without any option to filter in the query. It would be great if we had the ability to make filtered queries so that the threshold limitation is not hit. The rest of the features are great and this is the only setback.

### Steps to reproduce

1. Install the sppkg package in the app catalog.
2. On a blank page, add the webpart and in the configuration pane, choose a list with more than 5000 items.
3. Create a view in the large list added above which will show items less than 5000.
4. Configure the webpart with another list that has less than 5000.
5. An error is returned on the page that says view threshold is hit.

### Expected behavior

An error is displayed showing that the view threshold is hit.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.19.0

**Comment by albegut** [comment]
Hi @yvsuhas, I've just checked the case you are reporting and I could filter by custom view without any problem.

I've followed the next steps:

1. The list has more than 10.000 elements

![image](https://user-images.githubusercontent.com/9661096/172601047-0b9aeaa5-e04b-4669-889c-c610f8c37569.png)

2. I've create a view that retrieve 3001 elements 

![image](https://user-images.githubusercontent.com/9661096/172601192-8face613-609d-42aa-8331-7ea5d5b81936.png)

3. And I've configured the sample to get data from 2 different lists, one small and the large list with custom view

![image](https://user-images.githubusercontent.com/9661096/172601744-c388c601-47b1-4ad4-82ea-bae5a590599a.png)

4. The sample get all the information wihout any errors 

![image](https://user-images.githubusercontent.com/9661096/172601884-14041ead-3880-4bd0-b874-f28acd02985e.png)

Please tell me if the steps are different in order to reproduce the bug and be able to fix it

Thank you in advance!
