### ISSUE TITLE
react-page-navigator - first item in navigation incorrect

### ISSUE THREAD

**Issue by JoeAyre** [pnp/sp-dev-fx-webparts#2459]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-page-navigator

### Author(s)

@aakashbhardwaj619

### What happened?

It seems that the first header in the page content gets added as the parent node of the page navigation regardless of what it is.
From there on, the page navigation honours the level of header (H3 is nested under H2, etc.) but the first 'parent' node of the navigation seems to just reflect whatever that first header in the page content is, and every other header is a child of that.

I have a page where the first header is an H2, then the next header is another H2. I would expect these to be on the same level, but they are not - see image below.

![image](https://user-images.githubusercontent.com/36215002/160327359-961fe407-bf26-49b6-b302-a60a3400dc53.png)

### Steps to reproduce

1. Add the PageNavigator web part on the page
2. Add some content using various headers, starting with an H2, then another H2, then some H3s, then another H2 (for example).
3. Look at the PageNavigator web part (on page refresh)

### Expected behavior

PageNavigator web part to start with the first header and honour header levels - H1s all level with other H1s, H2s all level with other H2s, H3s all level with other H3s

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

I couldn't get this working, sorry!

**Comment by JoeAyre** [comment]
Author updated - sorry about that!

**Comment by mikezimm** [comment]
@JoeAyre , @aakashbhardwaj619 ,

I think the issue with your particular test is that the first header you have is h2.  If you start with an h1, it does adapt quite well (screenshot #1 of my test)

Starting with h2 (or h3) does throw off the logic.  I thought it would be an easy adjustment to make but after a few hours have come to the conclusion, it's may not be that easy.  In fact it might be downright painful to try and build logic to adapt to all the potential scenarios one might create including -

What if you started with an h2 and then followed up with an h1 later on.

For my particular use case, I'm wanted the option to collapse the entire page under a heading so I added links 74-89 in the Service.ts as shown below the screenshot.

What this does is:  If first header is not h1, it will insert a parent node with the Page Title or whatever you want.  Then everything up until a later h1 falls under that heading and can be collapsed.  Then the next h1 it finds is also a top level navigation element.

If you are really looking to start with h2s and follow with h1s (maybe because of styling),
Maybe you could try that logic, and then adjust the react component to take the links under the first node instead of the entire array.  Of course then you would have to do some adjustment for any headings that might be in the later.

In our particular use case, I'm going to just tell the user that you need to start with an h1 and maybe provide a way to style h1 tags if the real reason they want to start with h2 is because of styling like h1 might be 'to big' for their tastes.

Anyway, hope that helps.

## Testing when first heading is h1

![image](https://user-images.githubusercontent.com/49648086/166361209-68d87c77-df2d-4747-9fd5-56edcbe26262.png)


## Adjusted code to insert a parent node when first heading on page is h2

![image](https://user-images.githubusercontent.com/49648086/166389937-c405d6b2-1d2c-4234-a46c-abe5c099a43f.png)



## copy-paste of my code

```typescript
            /**
             * Added this check in case the first header is NOT h1
             * If the first header is h2, it pushes an object that represents an h1 but uses the page Title  or Topic or whatever as a label
             * NOTE:  If first header is h3 and the second is an h2, both are at the same level (as if h2 ) under the auto-generated h1
             */
            if (anchorLinks.length === 0 && headingOrder > 2 ) {
              let firstAnchor = '';
              if ( jsonData.TopicHeader ) {
                firstAnchor = jsonData.TopicHeader + ' - TopicHeader';
              } else if ( jsonData.Title ) {
                firstAnchor = jsonData.Title + ' - Title';
              } else { firstAnchor = 'Page Contents'; }

              anchorLinks.push({ name: firstAnchor, key: 'PageContentsNode0', url: null, links: [], isExpanded: true,  });
            }
```
