### ISSUE TITLE
react-news - 

### ISSUE THREAD

**Issue by pallanagendra** [pnp/sp-dev-fx-webparts#3034]
### Disclaimer

Yes

### Sample

react-news

### Author(s)

@ReactIntern

### What happened?

On **npm i** command, i'm getting error
![reactNewsError](https://user-images.githubusercontent.com/37343530/192021962-bcd3f3e1-92ce-4281-bda7-9ad99e5270fb.jpg)

### Steps to reproduce

1.  Cloned the Project
2. run the npm i command
3. didn't completed

### Expected behavior

Completed execution of npm i command

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

× SharePoint Framework

Error: SharePoint Framework not found

**Comment by mohammadamer** [comment]
@pallanagendra 
Which nodejs version are you using? 
For this WebPart you should use 10.24.0 because the SharePoint Framework version is 1.12.1

I used 10.24.0 version to install packages then build and it went well.
![image](https://user-images.githubusercontent.com/19314043/194627799-95e9983e-5863-4274-9e05-94105563850a.png)
