### ISSUE TITLE
PowerApps doesn't not show on mobile device

### ISSUE THREAD

**Issue by catohauk** [pnp/sp-dev-fx-webparts#3683]
### Disclaimer

Yes

### Sample

react-enhanced-powerapps

### Contributor(s)

@hugoabernier

### What happened?

I have a simple powerapp showing a list form. It shows fine on desktop, but is blank om mobile (both chrome app and sharepoint app) Device is Apple iPhone 12 pro (latest OS).

Regular powerapp widget does show on the phone with the same power app. 

### Steps to reproduce

1. Create an app
2. Add to sharepoint page as widget
3. Open page on iPhone device

### Expected behavior

The app.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [X] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

Don't know

### What version of Node.js is required by the sample?

Don't know

### Paste the results of SPFx doctor

Not sure how to do this.

### Additional environment details

No other info.

**Comment by hugoabernier** [comment]
Thanks for reporting the issue @catohauk, however the samples provided in this repo are intended to be used as samples -- for learning purposes -- and are not supported. Since you weren't able to provide Node version, SPFx doctor results, or other relevant information to help narrow the issue down, I'll close this issue as we can not support web parts.
