### ISSUE TITLE
isHtmlString: true on list based components

### ISSUE THREAD

**Issue by llermaly** [pnp/sp-dev-fx-webparts#3714]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnp-js-sample

### Contributor(s)

@juliemturner 

### Question

Hi!, thanks for this great example.

What I'm trying to achieve is to enable the isHtmlString: true property to the lists contents, so I can crawl my website. 

I was able to do it in other samples just activating the  setting on the property name but it is not working on this one.

Could you please guide me? What I was trying to do initially was to trying to modify the description field to put the lists data in there without success.

Thanks.

**Comment by llermaly** [comment]
I found this link:

https://joaojmendes.com/2019/02/08/read-and-update-spfx-webpart-properties-from-code/

Is this the only way? looks like that means I will have to trigger a "revision" for the pages to  re-run the query?

**Comment by juliemturner** [comment]
I'm sorry I just saw this. And although I've read your question several times, It's not really clear to me what you're asking.

This sample was built ONLY as a sample to guide on using the PnPjs SDK. If this is a question about using the SDK I would suggest you submit an issue to that repository here: https://github.com/pnp/pnpjs and try to include more details about what you've tried and what your goal is.

If this is a question about architecture of a solution if you can be clearer on what your goal is I can attempt to assist you.

**Comment by llermaly** [comment]
Thanks @juliemturner , I want to make lists within webparts searchable via a crawler. Is there still the right place to ask?

**Comment by juliemturner** [comment]
So, I guess what you're saying is that you have someone putting a web part on a page and while the page is in edit mode they're adding data and you're saving that to the web part properties and then you want that data searchable?

If I'm following you then the very simple answer is, you can't achieve what you're looking to do in that manner. What you want to do instead is create a SharePoint list (or library) and read the data from it and then display it in the web part. If you want to provide a custom UI for adding/editing items in the list, then you can also do that and use PnPjs (which is a fluent UI SDK for accessing the underlying SharePoint REST API) to update/modify the items in the list. Then, by definition of how SharePoint works, the items in the list are searchable. The sample you show does just that, read from a list (all though it's a library in this case) and then updates the items in the list. 

Maybe you have other requirements, but base on the very little you're sharing that's the correct answer.

**Comment by llermaly** [comment]
I'm consuming from an external list using pnp, but I can not see the list content when I check for the ContentCanvas1 field using the API (this is the API that the crawler uses) : 

`https://xxx.sharepoint.com/sites/dev/_api/web/lists/getbytitle('Site Pages')/items?$filter=FileLeafRef eq 'example.aspx'`

To fix that I put the list elements as metadata properties this way:

```
  public async onInit(): Promise<void> {
    this._environmentMessage = await this._getEnvironmentMessage();

    this._sp = getSP(this.context);
    const spCache = spfi(this._sp).using(Caching({ store: "session" }));

    const response: IResponseItem[] = await spCache.web.lists
    .getByTitle("React List")
    .items.select("Id", "Title", "FileLeafRef", "CustomField")
    .expand()();

    const items: IFile[] = response.map((item: IResponseItem) => {
        return {
          Id: item.Id,
          Title: item.Title || "Unknown",
          CustomField: item.CustomField || "Unknown",
          Name: item.FileLeafRef,
        };
      });

      this.properties.list = items;
      this.properties.searchableList = "React List:" + items.map((item: IFile) => item.Title).join(", ");
      await super.onInit();
  }
```

The problem with this is if the list changes (let's say someone adds or removes listitems) my ContentCanvas1 field will not reflect this change.

**Comment by juliemturner** [comment]
>but I cannot see the list content when I check for the ContentCanvas1 field using the API (this is the API that the crawler uses)

So, you've built (or are using) some other system that crawls the web parts on the page and then "indexes" that for search purposes? I don't understand the scenario here. That is not any kind of OOB Microsoft 365 solution. Is this some 3rd party product or a home grown solution?

**Comment by llermaly** [comment]
Yes, I'm using a python connector that connects to the API to read from sharepoint, then index the data elsewhere

**Comment by juliemturner** [comment]
Well... all I can think to myself is why. Since you don't seem inclined to share your end goal, I guess all I can tell you is that what you're trying to accomplish isn't really going to work well. All that data is not meant to be serialized to the web part properties; it's making your page slower than it would be otherwise. Further, the API you're accessing for page layouts is incredibly fragile since it's a 1st party api and could change out from under you at any time. I can give you a possible solution in that you could implement a webhook in a server or cloud-based resource to be triggered when updates are made to list items and then push the data to wherever "elsewhere" is... that would be more practical... but at the same time I don't know what elsewhere is used for or what the goal is. If I were trying to search the content in SharePoint (or Microsoft 365) for some other purpose, I would be using the SharePoint or Graph Search endpoints to accomplish that.

At this point I'm not sure how much more help I, or frankly anyone else, can be. Long story short that is not what web properties were meant for and the scenario you're describing just really isn't sustainable.

**Comment by llermaly** [comment]
Sorry, I just wanted to keep it simple. The end goal is to ingest our content in elasticsearch to create a unified search experience with other sources. The connector that ingests the sharepoint sites data consumes this API. In the past we used sharepoint server and we could see the lists within pages, but with sharepoint online looks like it's different. 

If there is a different API we can use for this purpose would be awesome to know which one it is. My initial thought was the same. SPFX are clientside and the connector is hitting the API serverside so there is no way to keep things on sync.

I appreciate your quick answer.

**Comment by juliemturner** [comment]
So, the content you're trying to ingest is list/library data or are you actually trying to scrape the text content from pages as well? Because if you don't need the text content from pages then the better answer is to create a server site solution that registers a webhook on every list/library in every site. Then when the list/library has changes it will call your endpoint to notify you of the change and then you can retrieve them and update your separate content source. I've built this type of solution before for other organizations, so I know it to be effective. If you actually need the text content on the page then I would probably see if I could register a webhook on the pages library and to be notified of changes and then scape the html of the particular page that had changed.

**Comment by llermaly** [comment]
I need the content + the updated list content within that page. So I should add a trigger to the save action of the list that updates the webpart ContentCanvas1 field like this one? https://joaojmendes.com/2019/02/08/read-and-update-spfx-webpart-properties-from-code/ 

Or there is a special API to do this? I found this one:

https://learn.microsoft.com/en-us/sharepoint/dev/apis/webhooks/lists/overview-sharepoint-list-webhooks

So this middleware should subscribe to the list changes and then update every webpart that references that list if I'm understanding correctly.

**Comment by juliemturner** [comment]
>So I should add a trigger to the save action of the list that updates the webpart ContentCanvas1 field like this one

I don't think you can add a trigger to the save action of a modern list... but regardless....

>So this middleware should subscribe to the list changes and then update every webpart that references that list if I'm understanding correctly.

The middleware should subscribe to the list changes and then directly update your "data elsewhere"... why would you want to create the added step of pushing the same data that's into the list into a web part property bag to then ingest again. 

If you take list data out of the equation, what other types of data are you taking from web parts on pages?

**Comment by llermaly** [comment]
> The middleware should subscribe to the list changes and then directly update your "data elsewhere"... why would you want to create the added step of pushing the same data that's into the list into a web part property bag to then ingest again.

You have a point here. The idea behind doing it that way is separation of concerns, but yeah, sounds more efficient to do it that way.

> If you take list data out of the equation, what other types of data are you taking from web parts on pages?

It is : 

* Static content (text)
* Static content (react custom cards with static text)
* Content coming from Sharepoint Lists
* Content comment from react components that connects to Sharepoint lists
* Third party APIs content

So lets say a page contains static text, some react cards, and a list with top users. 

I want to be able to search by some of the users and see that page back , and keep the top users list updated, or close to up to date.

**Comment by juliemturner** [comment]
If it were me, I would be doing all of this server side using webhooks (the link to webhook overview docs is correct)... essentially watch for a list to change and get notifications and then crawl the updated content. If it were me, I would investigate using webhooks to get notified when page content it updated by attaching to the site pages library and then use that to trigger a crawl of that pages content, but instead of looking inside the web parts themselves just render the page server side, get the div that is the content of the page and get the inner html/inner text of the page and that would take care of any of the static content updates. A quick search lead me to [this article](https://www.zenrows.com/blog/scraping-javascript-rendered-web-pages#installing-the-requirements) that I only briefly glanced over but generally is what I'm suggesting. With those two methods you should have pretty good coverage. 

If it were me I would completely abandon the idea of getting content using the 1st party pages api, that way lies madness. But, if you decide to go down the pages api path then I would limit your scope as much as possible, maybe just to text web parts. I'm still pretty sure it could break out from under you at any moment.

**Comment by llermaly** [comment]
This is very insightful, thank you. I agree, using a headless browser to visit the page and run the javascript code aligns with the SPFX architecture.
