### ISSUE TITLE
CSS overwrite affecting the entire page body margin

### ISSUE THREAD

**Issue by makaylacmac2** [pnp/sp-dev-fx-webparts#3767]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-list-form

### Contributor(s)

@hugoabernier @sharepointknight @wobba @rgarita @vman 

### Question

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/124900620/94da30f1-25e6-4aec-8bf7-04e22ffe5fe7)

There seems to be custom CSS in this sample causing a margin to affect the entire body of the page. What can I change/uninstall to resolve this?

I am new to SPFx webpart development, but a coworker with more experience was at least able to determine that the CSS is inline.

**Comment by sharepointknight** [comment]
I'll look at this this week.

Ryan

Sent from Surface Duo
________________________________

**Comment by makaylacmac2** [comment]
Thank you! The attachments also are not being uploaded, if you happen to see an obvious error. I was considering rewriting the attachments file with the pnp library, but I haven’t fully thought that through yet. This is where that idea is coming from https://sharepoint.stackexchange.com/questions/240436/spfx-how-to-add-item-in-sharepoint-list-with-attachment

Makayla Harder

Makayla Harder
________________________________

**Comment by sharepointknight** [comment]
I am looking at the code and I am not seeing anything as part of this sample that is setting the margin in question. Do you have anything pointing to which file this is getting loaded from? I searched and there is nothing in the latest code that is setting a margin of 1rem anywhere nor is there anywhere where any margins are being added inline on the body.
Ryan
    On Friday, June 16, 2023 at 07:25:14 PM PDT, github-actions[bot] ***@***.***> wrote:  
 
 


Please note that this issue will be closed within 24 hours because it has been flagged as having invalid authors. Read the guidance and @mention the authors so they can respond to you.
