### ISSUE TITLE
Error npm install react-birthdays

### ISSUE THREAD

**Issue by jwill1210** [pnp/sp-dev-fx-webparts#3999]
### Disclaimer

Yes

### Sample

react-birthdays

### Contributor(s)

mendes

### Question

Apologies @men im new to spfx, can someone help me how to resolve my issue?
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/12828699/eebb5f8b-faf8-4de1-8e9a-5ce38f90557b)

**Comment by jwill1210** [comment]
@joaojmendes thanks in advance

**Comment by danielDigitalArt** [comment]
I also had problems here, but they seem to be different. For me it found python version 2.7.15 while in your log it found 3.11 and then complained about the print function, maybe it will work for you if you install python 2.7 and tell the cli to use this instead.

I had a different err,r where it complained about Microsoft.Cpp.Default.props were not found. It seemed to be fixed by installing build tools (npm install --global --production windows-build-tools), though i am not really sure, because the installation of the packages, multiple rollbacks, deletions of node_module folders etc. takes a lot of hours, so i do not exactly know what fixed it.
