### ISSUE TITLE
Filter users based on AD attribute

### ISSUE THREAD

**Issue by PikeSal** [pnp/sp-dev-fx-webparts#4683]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-directory

### Contributor(s)

@joaomendes

### Question

We have an AD attribute JobTitle to exclude users from appearing in search results, how do i use this attribute to exclude users that shouldn't appear in React People directory webpart results.

**Comment by gretchunkim** [comment]
You can't using the "React Directory" as is condition. 

1st:  By design, it's using SharePoint User Profile services and properties and not straight to AD properties. 
2nd: It's limited to the following specific properties in SharePoint User profile service:
`["FirstName", "LastName", "PreferredName", "WorkEmail", "OfficeNumber", "PictureURL", "WorkPhone", "MobilePhone", "JobTitle", "Department", "Skills", "PastProjects", "BaseOfficeLocation", "SPS-UserType", "GroupId"];

You see how AD user properties is not listed? it's not 1:1  match between these two services. 

    `
