### ISSUE TITLE
Bug in SPFieldDateEdit.tsx in react-list-form for German UI

### ISSUE THREAD

**Issue by Jan-Kruse** [pnp/sp-dev-fx-webparts#487]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

DateFormFields should work in German UI.

## Observed Behavior

After selecting a date, the date is not displayed in the text box. The value is stored in the state.

## Steps to Reproduce

After selecting a date, the date is not displayed in the text box. The value is stored in the state.

This is caused by a strange date format in German UI. SPO returns the date as "DD.MM.YYYY H.m". Moment.JS identifies this as invalid. This can be solved by supplying a format string for this date format.

**Comment by hugoabernier** [comment]
@Jan-Kruse did you ever get this issue resolved?

I'll go ahead and close this issue as it is pretty old. If you're still having problems with this, feel free to open a new issue and, hopefully, we can get a fresh set of eyes to look at this and get you the help you deserve.

We also welcome pull requests in this repository; if you fixed the issue, feel free to post your changes so that others can benefit from your solution.

Thank you again for bringing this to our attention.
