### ISSUE TITLE
TodoContainer.tsx TypeScript Error

### ISSUE THREAD

**Issue by WagnerGit** [pnp/sp-dev-fx-webparts#500]
I have this issue when I run 'Gulp Serve':

src\webparts\todo\components\TodoContainer\TodoContainer.tsx(45,29): error TS2349: Cannot invoke an expression whose type lacks a call signature

**Comment by FranckyC** [comment]
Hi @WagnerGit , this error is due to an incorrect version of the _"immutability-helper"_  npm package.
A quick fix is to update the _package.json_ file and set the version like this (without the caret):

`"immutability-helper": "2.2.0"`

Then run a **npm i** and you're good to go! I will make a PR to fix this issue.
