### ISSUE TITLE
Delete scenario not working within React-todo-basic sample

### ISSUE THREAD

**Issue by yoghcl** [pnp/sp-dev-fx-webparts#511]
## Category

- [ ] Question
- [X] Bug
- [ ] Enhancement

# I am getting following error while deleting a task in the React-todo-basic sample. The error is happening somewhere with in the delete method

https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-todo-basic/src/webparts/todo/dataProviders/SharePointDataProvider.ts 

**_- TypeError: Failed to construct 'Response': Response with null body status cannot have body
- Uncaught (in promise) TypeError: This request was part of an SPHttpClientBatch that failed_**

**Comment by hugoabernier** [comment]
@yoghcl did you ever get this issue resolved?

I'll go ahead and close this issue as it is pretty old. If you're still having problems with this, feel free to open a new issue and, hopefully, we can get a fresh set of eyes to look at this and get you the help you deserve.

We also welcome pull requests in this repository. If you solved this problem yourself, feel free to submit your changes so that others can benefit from your solution.

Thanks again for bringing this to our attention.
