### ISSUE TITLE
react-page-navigator Question

### ISSUE THREAD

**Issue by chasquad** [pnp/sp-dev-fx-webparts#5121]
### Disclaimer

Yes

### Sample

react-page-navigator

### Contributor(s)

@hugoabernier 

### Question

Has anyone been able to build this solution.  I'm not a developer, and we're so small that we don't have any.  Could someone build and provide the SP package?  That would be awesome!

**Comment by ivy86** [comment]
We are struggling as well. A downloadable app package would be greatly appreciated.

**Comment by hugoabernier** [comment]
> We are struggling as well. A downloadable app package would be greatly appreciated.

  ## Requests for packaged solutions
  
  Thank you for reaching out! Please note that the samples in this repository are intended solely for educational purposes. Unfortunately, we are unable to provide a built or packaged solution.
  
  For your safety and security, we strongly advise against downloading or installing any packaged solutions from the internet without thoroughly reviewing their contents first. Additionally, please ensure to consult your organization’s security guidelines before employing any samples from this repository in a production environment.
  
  For more detailed information, please review our [support guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/SUPPORT.md).

  Feel free to open a new issue if you'd like to request for help building the solution. Make sure to provide all the requested information so that we can help you as quickly as possible.
  
  We appreciate your understanding and cooperation!

**Comment by chasquad** [comment]
Thank you for sharing your insights. I completely resonate with your concerns regarding the shift towards SPFx. As a SharePoint Administrator since the early days of SharePoint, I've witnessed various evolutions within the platform. The move to SPFx, while bringing many benefits in terms of modern web development capabilities and integration options, does indeed present a significant challenge for those of us who are not traditional developers.

The expectation to adapt to a more development-oriented framework can be daunting. It's not just about learning new skills but also about the time and resources needed to effectively make this transition while maintaining our current responsibilities. Microsoft's emphasis on SPFx certainly advances the platform's capabilities, but it also highlights a growing gap that needs to be addressed: the support and resources available to admins who now have no choice but to upskill.

One potential pathway forward could be advocating for more structured learning paths specifically tailored for SharePoint administrators who don't need to develop (write code) but simply need to be able to download and build github samples/solutions.  Additionally, more comprehensive **community support** and real-world examples of SPFx implementations could help bridge this gap.

Recognizing the diversity of roles affected by this technological shift, it's crucial for Microsoft and the community to support a broader base of professionals to adapt effectively. 

Remember that we're not all developers.  We don't necessarily have all of the tools loaded onto our computers.  We definitely don't have every version of every component that is needed to use these "samples" correctly. And, many of us work for non-profits and/or small companies who do not have the resources to have full time developers on staff.

**Comment by hugoabernier** [comment]
> Thank you for sharing your insights. I completely resonate with your concerns regarding the shift towards SPFx. As a SharePoint Administrator since the early days of SharePoint, I've witnessed various evolutions within the platform. The move to SPFx, while bringing many benefits in terms of modern web development capabilities and integration options, does indeed present a significant challenge for those of us who are not traditional developers.
> 
> The expectation to adapt to a more development-oriented framework can be daunting. It's not just about learning new skills but also about the time and resources needed to effectively make this transition while maintaining our current responsibilities. Microsoft's emphasis on SPFx certainly advances the platform's capabilities, but it also highlights a growing gap that needs to be addressed: the support and resources available to admins who now have no choice but to upskill.
> 
> One potential pathway forward could be advocating for more structured learning paths specifically tailored for SharePoint administrators who don't need to develop (write code) but simply need to be able to download and build github samples/solutions. Additionally, more comprehensive **community support** and real-world examples of SPFx implementations could help bridge this gap.
> 
> Recognizing the diversity of roles affected by this technological shift, it's crucial for Microsoft and the community to support a broader base of professionals to adapt effectively.
> 
> Remember that we're not all developers. We don't necessarily have all of the tools loaded onto our computers. We definitely don't have every version of every component that is needed to use these "samples" correctly. And, many of us work for non-profits and/or small companies who do not have the resources to have full time developers on staff.

While I understand the diversity of our community, and that not everyone is a SPFx developer, it does not change the fact that this repository is only for education purposes; it is not intended to be used for downloading samples.

I agree with the gap in learning paths, and that's why we -- the community -- have started the [community docs initiative](https://docs.microsoft.com/microsoft-365/community/?WT.mc_id=m365-12936-cxa), to help address these gaps as a community. You can contribute to it, and/or create an issue to ask if someone else in the community is able to help.

You can also join a {Sharing is Caring]{https://aka.ms/sharing-is-caring) online workshop to learn how to configure your workstation, but -- as you mentioned -- this may not be a viable option for those who don't have the dedicated resources to do so.

The feedback you provided is one that we have often provided Microsoft with. To add your voice to ours, I would encourage you to provide your feedback directly to Microsoft. Keep in mind that this repository is a Community-led initiative, and therefore not supported by Microsoft. While there are many Microsoft contributors here, they do so outside of their day-to-day work at Microsoft, on a volunteer basis.

For more extensibility options, I would recommend that you look at the SharePoint app store for pre-built packages.

I hope that this helps?
