### ISSUE TITLE
react-script-editor - 

### ISSUE THREAD

**Issue by adumith** [pnp/sp-dev-fx-webparts#5195]
### Disclaimer

Yes

### Sample

react-script-editor

### Contributor(s)

@wobba @salascz @felixbohnacker

### Question

Maybe I need new lenses, but I have not been able to find the link to download the **sppkg** file and upload it into my SharePoint.

Could you help me?

**Comment by felixbohnacker** [comment]
You will need to create the package yourself as described here: https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor#minimal-path-to-awesome

However, please keep in mind that using this web part in real-world scenarios is not recommended for security reasons.

**Comment by salascz** [comment]
Hi @adumith,
as written above, you should keep in mind there might be security risks by making this sample solution available globally.

In addition, manifest of this solution requires to enable custom script on the site, before you use the web part (the web part cannot be installed on the site otherwise)

**Comment by wobba** [comment]
@adumith read the entire readme closely and you will be able to make it work. Still curious why you would use it instead of creating a governed SPFx solution with the code instead. This way no one can arbitrary change the code.
