### ISSUE TITLE
Issue loading SPFX webpart with safari browser

### ISSUE THREAD

**Issue by mantrawadirama** [pnp/sp-dev-fx-webparts#580]
Hi Team,

I have a build webpart using SPfX. Ran into following issues 
  We use custom master page which uses javascript and jquery 
     files. After SPFX webpart gets deployed getting an error        
     "Multiple anonymous defines in module". 

Issue is related to safari browser on Mac, Ipad and Iphone.
Thanks
Rama

Thanks for your contribution! Sharing is caring.

**Comment by JayakumarB** [comment]
Hi @mantrawadirama ,

I too face the same issue at my initial stage. Since SPFx webaparts appended as a Javascript there will be some conflict between the already referred script files and SPFx file.

If you have added any other custom scripts in body tag of master page please remove it and add it in Head tag it will work.

Refer [this](Previously the custom scripts were added in Body tag and I moved it to head tag the issue resolved now)

**Comment by hugoabernier** [comment]
Closing this issue as it relates to general SPFx dev. Feel free to re-open this issue in https://github.com/sharepoint/sp-dev-docs
