### ISSUE TITLE
React Content Query WebPart improvements

### ISSUE THREAD

**Issue by brandon-murray** [pnp/sp-dev-fx-webparts#685]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors

@spplante 

## Desired Behavior

First of all, great work on this! Love the Handlebars templating. 

The old Content Query Web Part allows you to retrieve results from all webs in a site collection. The modern Highlighted Content Web Part allows you to do this as well as limit results to a hub site and its associated sites. The React Content By Query web part, however, requires you to specify a single site and single web within that site to pull results from.

It would be fantastic if the query part of this sample could be updated to allow the user to return results from all sites, all webs within a specified site, or all sites within a hub.

**Comment by spplante** [comment]
@brandon-murray this is basically an API limitation. When using the server side API, you have the choice between an `SPSiteDataQuery` or a `SPQuery`. The original Content by Query WebPart uses the SPSiteDataQuery, which allows to not only target a specific list but also target a whole site collection. However, in CSOM, the SPSiteDataQuery does not exist, and the only way to do a CAML query using the CSOM API is by using the equivalent of a SPQuery, which does not provide any option to look within a whole site collection, it really is exclusively for a specific list.

In order to accomplish this using CSOM, I would have to use the search, but at this point the whole "query building" experience wouldn't make sens because building a CAML query is totally different from building a search query, hence the reason why I think this should be a totally different WebPart.

What you are looking for is most likely something like the [React-Search-Refiners](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-search-refiners) which has also been modified to use Handlebars templating, but based on the search 👍
