### ISSUE TITLE
react-script-editor excessive console logs

### ISSUE THREAD

**Issue by bencleary** [pnp/sp-dev-fx-webparts#701]
- [x] Question
- [ ] Bug
- [ ] Enhancement

Firstly thank you or your work on these resources! I came across it and its awesome! Secondly i am assuming off the bat that this is something i have done wrong, that being said i looked and couldn't see anything specific about this.

Is it normal to have this amount of warnings and errors in the console? If yes then i assume this is down to SharePoints framework, if no then i will go back through the steps again.

![image](https://user-images.githubusercontent.com/11590157/49144947-8a3e1080-f2f6-11e8-98a8-9ff55c92fa54.png)

Thanks for your time.

**Comment by hugoabernier** [comment]
Thanks @bencleary for the kind comments. 

No, you didn't do anything wrong; there are often many console entries created by the web parts, the workbench and/or pages and (especially) Office UI Fabric.

Given the fact that this issue is a couple years old, I'll assume that you already figured that out, but I'm documenting a response here for future fellow SharePoint people with the same issue.
