### ISSUE TITLE
react-multilist-grid solution - new SPFx solution

### ISSUE THREAD

**Issue by narulasrinivas** [pnp/sp-dev-fx-webparts#854]
Hello Community & @joelfmrodrigues & @VesaJuvonen 

- [x] Question

react-multilist-grid SPFx solution is in 0.1.2 and OfficeCLI 365 project upgrade support SPFx solutions greater than 1.0.0 version. Below is the sample link

https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-multilist-grid

## Expected or Desired Behavior

Upgrade  react-multilist-grid solution which was build on SPFx v0.1.2 to SPFx v.17.1/v1.8.1 ?

## Observed Behavior

When I ran Office365 CLI to upgrade the solution. It gave me below report

`Error: Office 365 CLI doesn't support upgrading projects build on SharePoint Framework v0.1.2`

From Office365 CLI docs, it is clear that project update works only for projects built using SPFx v1.0.0 and greater versions. 

What is the best way to upgrade this solution? Any pointers?

Thanks for your contribution! Sharing is caring.

**Comment by joelfmrodrigues** [comment]
Hi @narulasrinivas

As the cli is not an option, I think the best approach would be to create a new SPFx project using the latest version and then copy the custom code from the old to the new project. Some things may need to be fixed after due to the SPFx changes over time, but most of it will probably work.
I don't know this sample well, but this is the approach I would follow if I had to update it.

Hope this helps
Joel
